/* Shared glossary — every lesson taps the same terms, the library searches them. */
window.TERMS = {
 app:{w:"App",
   p:"The thing on the phone. It is mostly a window and holds almost nothing itself — every number it shows, it had to go and ask for first.",
   v:"App trên điện thoại chỉ là cái cửa sổ. Nó không giữ dữ liệu; mọi con số nó hiển thị đều phải đi hỏi rồi mới có."},
 server:{w:"Server",
   p:"A computer in a data centre that never switches off, sitting there waiting to answer questions from apps. When people say \"the system is down\", they usually mean a server stopped answering.",
   v:"Máy chủ — máy tính chạy 24/7 trong trung tâm dữ liệu, chờ trả lời câu hỏi từ app. \"Hệ thống sập\" thường có nghĩa là máy chủ ngừng trả lời."},
 database:{w:"Database (people say \"DB\")",
   p:"Where information is written down and kept. Picture an enormous, very organised set of filing cabinets. It does not decide anything and it does not think — it stores things and hands them back when asked. Finding a record takes real time, which is why it is never instant.",
   v:"Cơ sở dữ liệu — nơi lưu thông tin, như một dãy tủ hồ sơ khổng lồ được sắp xếp rất kỹ. Nó không tự quyết định gì, chỉ cất và lấy ra khi được hỏi. Việc tìm ra bản ghi mất thời gian thật, nên không bao giờ tức thì.",
   r:"When a technical person says \"the DB\", this is what they mean. Every business application in the world sits on top of one."},
 core:{w:"Core banking system",
   p:"The bank's central system: its database plus every rule about money. It is the only place an account balance is genuinely true, and it is what auditors and the regulator look at. T24, Flexcube and Symbols are the common brand names in this market.",
   v:"Hệ thống lõi ngân hàng — cơ sở dữ liệu cộng toàn bộ quy tắc về tiền. Là nơi duy nhất số dư là thật, và là hệ thống mà kiểm toán với Ngân hàng Nhà nước soi vào.",
   r:"It was designed for branch counters and end-of-day batch runs, not for hundreds of thousands of people refreshing a phone app at once. That mismatch is the whole opportunity."},
 request:{w:"Request (also called a \"call\")",
   p:"One question sent from the app to a server, and one answer coming back. Opening a bank app home screen usually sends six to ten of them before anything appears on screen.",
   v:"Một lần app gửi câu hỏi tới máy chủ và nhận lại câu trả lời. Mở màn hình chính của app ngân hàng thường cần 6–10 lần như vậy."},
 latency:{w:"Latency",
   p:"The waiting time between asking and getting the answer, measured in milliseconds. One thousand milliseconds is one second. A screen that needs eight answers of 150 milliseconds each keeps the customer waiting well over a second before anything appears.",
   v:"Độ trễ — thời gian chờ từ lúc hỏi tới lúc có câu trả lời, tính bằng phần nghìn giây. 1000 phần nghìn giây = 1 giây."},
 cache:{w:"Cache (pronounced \"cash\")",
   p:"A copy of an answer, kept somewhere much closer and much faster, so the same question does not have to travel all the way to the original source again.",
   v:"Bộ nhớ đệm — bản sao của câu trả lời, giữ ở chỗ gần hơn và nhanh hơn, để khỏi phải đi hỏi lại nguồn gốc."},
 redis:{w:"Redis",
   p:"The product most banks use to do the caching. Software that sits in front of the core, keeps copies of answers, and hands them back in about one millisecond. It is a well-known open-source product, so the software itself is free — the memory it needs and the people who run it are not.",
   v:"Phần mềm cache phổ biến nhất. Đứng trước core, giữ bản sao câu trả lời và trả về trong khoảng 1 phần nghìn giây. Bản thân phần mềm miễn phí, nhưng bộ nhớ và đội vận hành thì không."},
 memory:{w:"Memory (RAM)",
   p:"A computer's short-term memory. Roughly a hundred times faster to read than a hard disk, but small, expensive per gigabyte, and wiped when the machine restarts. That trade-off is exactly why a cache is fast, and exactly why a bank never keeps its records there.",
   v:"Bộ nhớ tạm — đọc nhanh gấp khoảng 100 lần ổ cứng, nhưng dung lượng nhỏ, đắt, và mất sạch khi khởi động lại. Đó là lý do cache nhanh, và cũng là lý do ngân hàng không bao giờ lưu sổ sách ở đó."},
 hit:{w:"Cache hit / cache miss",
   p:"Hit: the answer was already in the drawer, so no trip to the vault. Miss: it was not there, so someone had to go to the core — and then kept a copy for next time.",
   v:"Hit = đã có sẵn trong ngăn kéo. Miss = chưa có, phải đi tới core lấy, rồi giữ lại một bản sao cho lần sau.",
   r:"\"What is your hit rate?\" means: out of a hundred questions, how many were answered from the drawer. Ninety-five percent means the core only had to handle five."},
 ttl:{w:"TTL — time to live",
   p:"An expiry stamp on a copy: keep this for thirty seconds, then delete yourself automatically. The same simple mechanism is what makes an OTP expire, what logs you out after idle time, and what unlocks an account after a temporary lock.",
   v:"Thời hạn sống — dán hạn dùng lên bản sao, hết hạn thì tự xoá. OTP hết hiệu lực, tự động đăng xuất, khoá tài khoản tạm 15 phút — tất cả đều chạy bằng cơ chế này.",
   r:"Too long and customers see old numbers. Too short and you are back to asking the core every time. Deciding it per screen is a business conversation, not a technical one — which means you can lead it."},
 invalidate:{w:"Invalidate",
   p:"Deliberately throwing a copy away the moment the real value changes — for example the instant a transfer lands in an account.",
   v:"Chủ động xoá bản sao ngay khi giá trị thật thay đổi, ví dụ đúng lúc tiền về tài khoản."},
 authpath:{w:"Authorisation path",
   p:"The moment the bank decides yes, this money can leave this account. Everything checked in that moment has to be exact, and has to come from the core.",
   v:"Đường duyệt lệnh — khoảnh khắc ngân hàng quyết định cho tiền rời khỏi tài khoản. Mọi thứ kiểm tra ở khoảnh khắc đó phải chính xác tuyệt đối và phải lấy từ core."},
 idem:{w:"Idempotency key",
   p:"A ticket number attached to an instruction. If the same ticket number arrives twice, the bank knows it is one instruction repeated, not two payments — so the money leaves once. The word itself just means \"doing it twice has the same effect as doing it once\".",
   v:"Mã vé gắn vào một lệnh. Cùng một mã vé đến hai lần thì ngân hàng hiểu đó là một lệnh bị lặp, không phải hai lệnh chuyển tiền — nên tiền chỉ ra một lần. Bản thân từ này nghĩa là \"làm hai lần cũng ra kết quả như làm một lần\".",
   r:"Ask a bank \"how do you handle a double tap on a bad connection?\" Very few salespeople do, and everybody in the room will notice."},
 session:{w:"Session",
   p:"The record that says you are currently logged in. It is kept for a while and then expires, which is why an app signs you out after a period of doing nothing.",
   v:"Phiên đăng nhập — bản ghi cho biết bạn đang đăng nhập. Nó tồn tại một lúc rồi hết hạn, nên app tự đăng xuất khi bạn không dùng."}
};

/* which lesson introduces each term */
window.TERM_LESSON = {};
Object.keys(window.TERMS).forEach(function(k){ window.TERM_LESSON[k] = window.TERMS[k].l || "01"; });
