/* Shared glossary — every lesson taps the same terms, the library searches them.
   Third block names the table, entity or FRS code the term maps to in sme-finance-scm. */
window.TERMS = {
 dongtien:{w:"Cash flow",
   p:"Money actually entering and leaving the bank account, on the day it truly moves. Not revenue, not profit — just: is the account thicker or thinner today than it was yesterday.",
   v:"Dòng tiền — tiền thật đi vào và ra khỏi tài khoản, theo đúng ngày nó chuyển. Không phải doanh thu, không phải lợi nhuận.",
   r:"cashflow-service · CashFlowEntry with FlowDirection = IN | OUT. One row for each moment money genuinely moved."},
 doanhthu:{w:"Revenue",
   p:"The value of goods sold, written into the books the day they are delivered and invoiced — even when the customer will not pay for another forty-five days. This is where technical people go wrong most often: selling 360 million does not mean 360 million is in the account.",
   v:"Doanh thu — ghi vào sổ ngay lúc giao hàng và xuất hoá đơn, kể cả khi 45 ngày nữa khách mới trả. Bán được 360 triệu không có nghĩa là có 360 triệu trong tài khoản.",
   r:"Revenue produces an Invoice in status ISSUED — and no CashFlowEntry at all. Money only appears when an InvoicePayment does."},
 loinhuan:{w:"Profit",
   p:"Revenue minus costs, on paper. A company can be profitable three months running and still be unable to pay salaries in month two — because the profit is on paper and salaries are paid in cash.",
   v:"Lợi nhuận — doanh thu trừ chi phí, tính trên sổ. Có lãi ba tháng liền vẫn có thể không đủ tiền trả lương tháng thứ hai.",
   r:"Profit is not a table in this system — report-service derives it. What the system tracks day by day is cash flow."},
 phaithu:{w:"Accounts receivable",
   p:"Money customers owe you. Delivered, invoiced, unpaid. It is an asset on the balance sheet and you cannot spend it — nobody pays staff with a receivable.",
   v:"Khoản phải thu — tiền khách đang nợ mình. Là tài sản trên sổ nhưng không tiêu được.",
   r:"Invoice.direction = RECEIVABLE, and on the credit side a CreditExposure with ExposureDirection = RECEIVABLE."},
 phaitra:{w:"Accounts payable",
   p:"Money you owe suppliers. Goods received, not yet paid for. It sounds bad and it is in fact free funding: every day you have not paid is a day the money is still in your account.",
   v:"Khoản phải trả — tiền mình đang nợ nhà cung cấp. Nghe xấu nhưng thực ra là nguồn vốn miễn phí.",
   r:"Invoice.direction = PAYABLE. Same invoices table, one column different — which is why changing that value changes the books."},
 congno:{w:"Công nợ",
   p:"One Vietnamese word covering both sides at once — what a partner owes you and what you owe them. When an accountant says \"công nợ với đối tác A\", they mean every balance still open between you and A, who may well be a customer and a supplier at the same time. English has no single word for it, which is exactly why it trips people up.",
   v:"Từ tiếng Việt gộp cả hai chiều phải thu và phải trả với cùng một đối tác.",
   r:"credit-service · CreditExposure. One partner can hold exposure in both directions — that is the premise of the two-way offset in CM-21."},
 tonkho:{w:"Inventory",
   p:"Goods bought, paid for, not yet sold. Your money is sitting still in a warehouse in the shape of boxes. The fuller the warehouse, the thinner the cash — which is why \"sales are slow\" and \"we have no money\" always arrive together.",
   v:"Hàng tồn kho — tiền của bạn đang nằm im trong kho dưới dạng thùng hộp.",
   r:"scf-service · InventoryItem. In inventory financing this same stock is what gets pledged — CollateralPledge."},
 vonluudong:{w:"Working capital",
   p:"The money a business must put up to keep its cycle turning: buy stock, hold it, wait to be paid. This entire system exists to make that number smaller.",
   v:"Vốn lưu động — số tiền phải bỏ ra để giữ vòng quay kinh doanh chạy được.",
   r:"No table is called working capital. It is the sum of three things the system does track: inventory + receivables − payables."},
 dio:{w:"DIO — days inventory outstanding",
   p:"How many days stock sits in the warehouse before it sells. Bought on day 1, sold on day 21, DIO is 20.",
   v:"Số ngày hàng nằm kho trước khi bán được.",
   r:"cash_flow_metrics.dio_days, written by the nightly job (CF-07)."},
 dso:{w:"DSO — days sales outstanding",
   p:"How many days pass between issuing the invoice and the money actually arriving. DSO of 45 means every đồng of revenue waits a month and a half to become cash. Lower is healthier.",
   v:"Số ngày khách trả tiền sau khi xuất hoá đơn. Càng thấp càng khoẻ.",
   r:"cash_flow_metrics.dso_days, derived from dso_settled_count and dso_total_days (CM-03)."},
 dpo:{w:"DPO — days payable outstanding",
   p:"How many days you keep the money before paying suppliers. The only one of the three where higher is better — but stretch it too far and suppliers walk away or raise the price.",
   v:"Số ngày mình giữ được tiền trước khi phải trả nhà cung cấp. Cao là tốt, nhưng kéo dài quá thì nhà cung cấp nghỉ chơi.",
   r:"cash_flow_metrics.dpo_days (CM-03). \"Suggest optimal payment terms\" in CM-04 is this number being pushed up."},
 ccc:{w:"CCC — cash conversion cycle",
   p:"The number of days your money is out of the account before it comes back: DIO + DSO − DPO. A CCC of 35 means that every cycle, you fund thirty-five days out of your own pocket. It is the most important number in this lesson.",
   v:"Chu kỳ chuyển đổi tiền mặt = DIO + DSO − DPO. Số ngày bạn phải tự bỏ tiền túi nuôi việc kinh doanh của chính mình.",
   r:"cash_flow_metrics.ccc_days (CF-07). The other three columns are its inputs."},
 burnrate:{w:"Burn rate",
   p:"How much thinner the account gets each month. There are two of them and they are not the same: gross burn is everything spent in a month, net burn is what is actually missing once income is subtracted.",
   v:"Tốc độ đốt tiền. Gross burn = tổng chi mỗi tháng; net burn = phần thực sự hụt sau khi trừ tiền thu về.",
   r:"cash_flow_metrics.burn_rate (net) and gross_burn_rate. Two columns because they answer two different questions, and neither can be derived from the other."},
 runway:{w:"Runway",
   p:"With the cash on hand and the current burn, how many days until it is gone. This is the number that keeps a managing director awake, and the one every early warning in the system is serving.",
   v:"Số ngày cầm cự — còn bao nhiêu ngày nữa thì hết sạch tiền.",
   r:"cash_flow_metrics.runway_days — null when net cash flow is positive, because a company that is not running out has no days-left figure."},
 thanhkhoan:{w:"Liquidity",
   p:"Being able to pay what falls due, on the day it falls due. Losing it kills a company — even one that is profitable with a full warehouse. Bankruptcy is almost always death by liquidity, not death by loss.",
   v:"Thanh khoản — khả năng trả các khoản đến hạn đúng lúc. Phá sản gần như luôn là chết vì mất thanh khoản, không phải vì lỗ.",
   r:"CashAlert with a CashAlertType for a forecast shortfall against a configured threshold (CF-11)."},
 hoadon:{w:"Invoice (hoá đơn)",
   p:"The legal record of one sale: who sold, who bought, how much, due when. It is not money, and it is not a free-text note — it is a document with legal force.",
   v:"Hoá đơn — chứng từ pháp lý ghi nhận một lần bán hàng. Nó không phải là tiền.",
   r:"scf-service · Invoice. Note two deliberate absences: there is no OPEN status (in-term versus overdue is derived from due_date), and an issued invoice cannot be cancelled — Nghị định 70/2025 removed cancellation of e-invoices, so a mistake is fixed by a replacement (REPLACED)."},
 hanthanhtoan:{w:"Payment terms / due date",
   p:"The agreement on how many days after delivery the customer must pay. \"Net 45\" means forty-five days. It looks like an ordinary date field, and it is the thing that sets DSO — and through DSO, whether the company lives.",
   v:"Điều khoản thanh toán — \"Net 45\" là 45 ngày. Nhìn như một trường ngày tháng bình thường, nhưng nó quyết định DSO.",
   r:"Invoice.dueDate. A nightly job compares due_date with today to move invoices to OVERDUE — no user clicks that."},
 chietkhau:{w:"Invoice discounting (chiết khấu hoá đơn)",
   p:"Selling your own receivable to a financier for cash today, at a fee. Trading part of the profit for time. For a company short of cash, that is a very good trade.",
   v:"Chiết khấu hoá đơn — bán khoản phải thu của mình để lấy tiền ngay, chịu mất một khoản phí.",
   r:"FinancingProgram with ProgramType = INVOICE_DISCOUNTING (SCF-01, SCF-02)."},
 taitronguocdong:{w:"Reverse factoring (tài trợ ngược dòng)",
   p:"The same idea, started by the buyer. A large corporation confirms \"this invoice I will certainly pay\", so a small supplier borrows against the corporation's credit standing rather than its own — and the fee falls accordingly.",
   v:"Tài trợ ngược dòng — bên mua khởi xướng; nhà cung cấp nhỏ vay theo uy tín của tập đoàn lớn chứ không phải của chính mình, nên phí rẻ hơn hẳn.",
   r:"ProgramType = REVERSE_FACTORING (SCF-06). The invoice direction here is PAYABLE — the opposite of invoice discounting."},
 duno:{w:"Dư nợ — outstanding exposure",
   p:"The amount still open with one partner right now. It is the word an accountant reaches for to ask \"how much is still owed\", and it is what every limit, alert and aging report measures.",
   v:"Dư nợ — số tiền còn treo với một đối tác tại thời điểm này.",
   r:"credit-service · CreditExposure, status OUTSTANDING → SETTLED / OVERDUE / WRITTEN_OFF."},
 hanmuc:{w:"Credit limit (hạn mức)",
   p:"The ceiling on how much may be owed. Over the ceiling the system blocks, or escalates for another approval. It is a business number rather than a technical constraint — but code it wrong and the company loses real money.",
   v:"Hạn mức — trần số tiền được phép nợ. Vượt trần thì hệ thống chặn hoặc bắt duyệt thêm cấp.",
   r:"SupplierLimit in scf-service (financing limit) and RiskThreshold in credit-service (risk ceilings, CM-11, CM-12)."}
};

/* which lesson introduces each term */
window.TERM_LESSON = {};
Object.keys(window.TERMS).forEach(function(k){ window.TERM_LESSON[k] = window.TERMS[k].l || "01"; });
