/* Shared glossary — every lesson taps the same terms, the library searches them.
   Third block names the table, entity or FRS code the term maps to in sme-finance-scm. */
window.TERMS = {
 dongtien:{w:"Cash flow",
   p:"Money actually entering and leaving the bank account, on the day it truly moves. Not revenue, not profit — just: is the account thicker or thinner today than it was yesterday.",
   v:"Dòng tiền — tiền thật đi vào và ra khỏi tài khoản, theo đúng ngày nó chuyển. Không phải doanh thu, không phải lợi nhuận.",
   r:"cashflow-service · CashFlowEntry with FlowDirection = IN | OUT. One row for each moment money genuinely moved."},
 doanhthu:{w:"Revenue",
   p:"The value of goods sold, written into the books the day they are delivered and invoiced — even when the customer will not pay for another forty-five days. This is where technical people go wrong most often: selling 360 million does not mean 360 million is in the account.",
   v:"Doanh thu — ghi vào sổ ngay lúc giao hàng và xuất hoá đơn, kể cả khi 45 ngày nữa khách mới trả. Bán được 360 triệu không có nghĩa là có 360 triệu trong tài khoản.",
   r:"Revenue produces an Invoice in status ISSUED — and no CashFlowEntry at all. Money only appears when an InvoicePayment does."},
 loinhuan:{w:"Profit",
   p:"Revenue minus costs, on paper. A company can be profitable three months running and still be unable to pay salaries in month two — because the profit is on paper and salaries are paid in cash.",
   v:"Lợi nhuận — doanh thu trừ chi phí, tính trên sổ. Có lãi ba tháng liền vẫn có thể không đủ tiền trả lương tháng thứ hai.",
   r:"Profit is not a table in this system, and no report produces it either: report-service ships six management reports plus the statutory B03-DN cash flow statement, and no income statement at all. What the system tracks day by day is cash flow."},
 phaithu:{w:"Accounts receivable",
   p:"Money customers owe you. Delivered, invoiced, unpaid. It is an asset on the balance sheet and you cannot spend it — nobody pays staff with a receivable.",
   v:"Khoản phải thu — tiền khách đang nợ mình. Là tài sản trên sổ nhưng không tiêu được.",
   r:"Invoice.direction = RECEIVABLE, and on the credit side a CreditExposure with ExposureDirection = RECEIVABLE."},
 phaitra:{w:"Accounts payable",
   p:"Money you owe suppliers. Goods received, not yet paid for. It sounds bad and it is in fact free funding: every day you have not paid is a day the money is still in your account.",
   v:"Khoản phải trả — tiền mình đang nợ nhà cung cấp. Nghe xấu nhưng thực ra là nguồn vốn miễn phí.",
   r:"Invoice.direction = PAYABLE. Same invoices table, one column different — which is why changing that value changes the books."},
 congno:{w:"Công nợ",
   p:"One Vietnamese word covering both sides at once — what a partner owes you and what you owe them. When an accountant says \"công nợ với đối tác A\", they mean every balance still open between you and A, who may well be a customer and a supplier at the same time. English has no single word for it, which is exactly why it trips people up.",
   v:"Từ tiếng Việt gộp cả hai chiều phải thu và phải trả với cùng một đối tác.",
   r:"credit-service · CreditExposure. One partner can hold exposure in both directions — that is the premise of the two-way offset in CM-21."},
 tonkho:{w:"Inventory",
   p:"Goods bought, paid for, not yet sold. Your money is sitting still in a warehouse in the shape of boxes. The fuller the warehouse, the thinner the cash — which is why \"sales are slow\" and \"we have no money\" always arrive together.",
   v:"Hàng tồn kho — tiền của bạn đang nằm im trong kho dưới dạng thùng hộp.",
   r:"scf-service · InventoryItem. In inventory financing this same stock is what gets pledged — CollateralPledge."},
 vonluudong:{w:"Working capital",
   p:"The money a business must put up to keep its cycle turning: buy stock, hold it, wait to be paid. This entire system exists to make that number smaller.",
   v:"Vốn lưu động — số tiền phải bỏ ra để giữ vòng quay kinh doanh chạy được.",
   r:"No table is called working capital. It is the sum of three things the system does track: inventory + receivables − payables."},
 dio:{w:"DIO — days inventory outstanding",
   p:"How many days stock sits in the warehouse before it sells. Bought on day 1, sold on day 21, DIO is 20.",
   v:"Số ngày hàng nằm kho trước khi bán được.",
   r:"cash_flow_metrics.dio_days, written by the nightly job (CF-07)."},
 dso:{w:"DSO — days sales outstanding",
   p:"How many days pass between issuing the invoice and the money actually arriving. DSO of 45 means every đồng of revenue waits a month and a half to become cash. Lower is healthier.",
   v:"Số ngày khách trả tiền sau khi xuất hoá đơn. Càng thấp càng khoẻ.",
   r:"cash_flow_metrics.dso_days, derived from dso_settled_count and dso_total_days (CM-03)."},
 dpo:{w:"DPO — days payable outstanding",
   p:"How many days you keep the money before paying suppliers. The only one of the three where higher is better — but stretch it too far and suppliers walk away or raise the price.",
   v:"Số ngày mình giữ được tiền trước khi phải trả nhà cung cấp. Cao là tốt, nhưng kéo dài quá thì nhà cung cấp nghỉ chơi.",
   r:"cash_flow_metrics.dpo_days (CM-03). \"Suggest optimal payment terms\" in CM-04 is this number being pushed up."},
 ccc:{w:"CCC — cash conversion cycle",
   p:"The number of days your money is out of the account before it comes back: DIO + DSO − DPO. A CCC of 35 means that every cycle, you fund thirty-five days out of your own pocket. It is the most important number in this lesson.",
   v:"Chu kỳ chuyển đổi tiền mặt = DIO + DSO − DPO. Số ngày bạn phải tự bỏ tiền túi nuôi việc kinh doanh của chính mình.",
   r:"cash_flow_metrics.ccc_days (CF-07). The other three columns are its inputs."},
 burnrate:{w:"Burn rate",
   p:"How much thinner the account gets each month. There are two of them and they are not the same: gross burn is everything spent in a month, net burn is what is actually missing once income is subtracted.",
   v:"Tốc độ đốt tiền. Gross burn = tổng chi mỗi tháng; net burn = phần thực sự hụt sau khi trừ tiền thu về.",
   r:"cash_flow_metrics.burn_rate (net) and gross_burn_rate. Two columns because they answer two different questions, and neither can be derived from the other."},
 runway:{w:"Runway",
   p:"With the cash on hand and the current burn, how many days until it is gone. This is the number that keeps a managing director awake, and the one every early warning in the system is serving.",
   v:"Số ngày cầm cự — còn bao nhiêu ngày nữa thì hết sạch tiền.",
   r:"cash_flow_metrics.runway_days — null when net cash flow is positive, because a company that is not running out has no days-left figure."},
 thanhkhoan:{w:"Liquidity",
   p:"Being able to pay what falls due, on the day it falls due. Losing it kills a company — even one that is profitable with a full warehouse. Bankruptcy is almost always death by liquidity, not death by loss.",
   v:"Thanh khoản — khả năng trả các khoản đến hạn đúng lúc. Phá sản gần như luôn là chết vì mất thanh khoản, không phải vì lỗ.",
   r:"CashAlert with a CashAlertType for a forecast shortfall against a configured threshold (CF-11)."},
 hoadon:{w:"Invoice (hoá đơn)",
   p:"The legal record of one sale: who sold, who bought, how much, due when. It is not money, and it is not a free-text note — it is a document with legal force.",
   v:"Hoá đơn — chứng từ pháp lý ghi nhận một lần bán hàng. Nó không phải là tiền.",
   r:"scf-service · Invoice. Note two deliberate absences: there is no OPEN status (in-term versus overdue is derived from due_date), and an issued invoice cannot be cancelled — Nghị định 70/2025 removed cancellation of e-invoices, so a mistake is fixed by a replacement (REPLACED)."},
 hanthanhtoan:{w:"Payment terms / due date",
   p:"The agreement on how many days after delivery the customer must pay. \"Net 45\" means forty-five days. It looks like an ordinary date field, and it is the thing that sets DSO — and through DSO, whether the company lives.",
   v:"Điều khoản thanh toán — \"Net 45\" là 45 ngày. Nhìn như một trường ngày tháng bình thường, nhưng nó quyết định DSO.",
   r:"Invoice.dueDate. A nightly job compares due_date with today to move invoices to OVERDUE — no user clicks that."},
 chietkhau:{w:"Invoice discounting (chiết khấu hoá đơn)",
   p:"Selling your own receivable to a financier for cash today, at a fee. Trading part of the profit for time. For a company short of cash, that is a very good trade.",
   v:"Chiết khấu hoá đơn — bán khoản phải thu của mình để lấy tiền ngay, chịu mất một khoản phí.",
   r:"FinancingProgram with ProgramType = INVOICE_DISCOUNTING (SCF-01, SCF-02)."},
 taitronguocdong:{w:"Reverse factoring (tài trợ ngược dòng)",
   p:"The same idea, started by the buyer. A large corporation confirms \"this invoice I will certainly pay\", so a small supplier borrows against the corporation's credit standing rather than its own — and the fee falls accordingly.",
   v:"Tài trợ ngược dòng — bên mua khởi xướng; nhà cung cấp nhỏ vay theo uy tín của tập đoàn lớn chứ không phải của chính mình, nên phí rẻ hơn hẳn.",
   r:"ProgramType = REVERSE_FACTORING (SCF-06). The invoice direction here is PAYABLE — the opposite of invoice discounting."},
 duno:{w:"Dư nợ — outstanding exposure",
   p:"The amount still open with one partner right now. It is the word an accountant reaches for to ask \"how much is still owed\", and it is what every limit, alert and aging report measures.",
   v:"Dư nợ — số tiền còn treo với một đối tác tại thời điểm này.",
   r:"credit-service · CreditExposure, status OUTSTANDING → SETTLED / OVERDUE / WRITTEN_OFF."},
 hanmuc:{w:"Credit limit (hạn mức)",
   p:"The ceiling on how much may be owed. Over the ceiling the system blocks, or escalates for another approval. It is a business number rather than a technical constraint — but code it wrong and the company loses real money.",
   v:"Hạn mức — trần số tiền được phép nợ. Vượt trần thì hệ thống chặn hoặc bắt duyệt thêm cấp.",
   r:"SupplierLimit in scf-service (financing limit) and RiskThreshold in credit-service (risk ceilings, CM-11, CM-12)."},
 vat:{w:"VAT (thuế giá trị gia tăng)",
   p:"A tax the buyer pays and the seller merely collects on the state's behalf. An invoice for 100 million of goods is presented at 110 million; the extra 10 million lands in the company's bank account and belongs to the tax authority from the moment it arrives. The company holds it until the declaration period, then hands it over. Treat it as revenue and every margin figure on the screen is ten percent too generous.",
   v:"Thuế GTGT — người mua chịu, doanh nghiệp chỉ thu hộ nhà nước rồi nộp lại. Tiền thuế nằm trong tài khoản nhưng chưa bao giờ là tiền của mình.",
   r:"invoices.net_amount + tax_amount = total_amount, held together by ck_invoices_total. The declaration side lives in transaction-service · TransactionTax with TaxType = VAT and declare_status NOT_DECLARED → DECLARED → PAID (TM-08)."},
 hoadondientu:{w:"E-invoice (hoá đơn điện tử)",
   p:"An invoice that exists as a signed electronic record with a code issued by the tax authority, not as a piece of paper. The state holds its own copy, so the seller's system is a second copy rather than the original. That is the reason so many rules here read as refusals: the document is not yours to edit.",
   v:"Hoá đơn điện tử — chứng từ ký số, có mã do cơ quan thuế cấp; nhà nước giữ bản của họ nên hệ thống của mình chỉ là bản sao thứ hai.",
   r:"invoices.invoice_series, tax_lookup_code, seller_tax_code, buyer_tax_code, and verification_status = UNVERIFIED | VERIFIED_MANUAL (SCF-01, P1). This system only records the result of issuing — the signing happens in external invoice software."},
 dieuchinh:{w:"Adjustment / replacement invoice (hoá đơn điều chỉnh / thay thế)",
   p:"The two legal ways to correct an issued invoice, now that cancelling one is not. A replacement voids the original whole and carries the debt across; an adjustment leaves the original standing and books the difference. Both are new records that point back at the invoice they correct — neither is a state of the original.",
   v:"Hai cách hợp pháp để sửa một hoá đơn đã phát hành: thay thế (vô hiệu hoá bản gốc) hoặc điều chỉnh (giữ bản gốc, ghi phần chênh). Cả hai đều là bản ghi mới.",
   r:"invoices.original_invoice_id + adjustment_kind = REPLACEMENT | ADJUSTMENT, forced to travel together by ck_invoices_adjustment. A replacement moves the original to status REPLACED (NĐ 70/2025/NĐ-CP, 06 §5)."},
 phanbothanhtoan:{w:"Payment allocation (phân bổ thanh toán)",
   p:"Deciding which invoices one incoming transfer pays off. A customer sends one round sum against four invoices, so somebody has to say how much of it lands where. When nobody says, the system settles the oldest due date first. Every slice is a row, and the invoice's paid amount is nothing but the sum of those rows.",
   v:"Phân bổ thanh toán — gạch một khoản tiền về vào các hoá đơn. Không ai chỉ định thì gạch theo hạn cũ nhất trước (FIFO).",
   r:"invoice_payments, at most one row per (invoice, transaction) — uk_invoice_payments_invoice_txn, the guard against double-crediting a redelivered Kafka message. allocation_method = MANUAL | FIFO; invoices.paid_amount is recomputed from the sum, never incremented (TM-21)."},
 quahan:{w:"Overdue (quá hạn)",
   p:"Past the due date with money still outstanding. It sounds like something a user reports, and it is not: it falls out of comparing two values the system already holds. Nobody presses a button, and the invoice does not have to be touched for it to happen.",
   v:"Quá hạn — đã qua ngày đến hạn mà chưa thu đủ. Không ai bấm nút; hệ thống tự suy ra từ due_date.",
   r:"InvoiceStatus.OVERDUE, set by the nightly scf job on due_date < today AND paid_amount < total_amount, for statuses ISSUED, PARTIALLY_PAID, FINANCING and FINANCED (06 §5.1, SCF-03). It publishes no event — credit-service counts its own days_overdue independently."},
 chungtu:{w:"Chứng từ — source document",
   p:"The piece of paper or file that proves a transaction really happened: the supplier's invoice, the bank's uỷ nhiệm chi, a signed phiếu chi, the contract. In Vietnamese accounting it is not an attachment to the entry — it is what gives the entry the right to exist. An entry with no chứng từ behind it is a claim nobody has to believe, and a cost the tax authority can strike out.",
   v:"Chứng từ — giấy tờ chứng minh một nghiệp vụ đã thực sự xảy ra. Không có chứng từ thì bút toán không có căn cứ, và chi phí đó có thể bị cơ quan thuế loại.",
   r:"document-service · Document with DocType = INVOICE | RECEIPT | CONTRACT | PAYMENT_SLIP, tied to an entry through transaction_documents (TM-04). Marking a payment EXECUTED is refused without one — requireExecutionEvidence in TransactionService."},
 vetkiemtoan:{w:"Audit trail — vết kiểm toán",
   p:"The permanent record of who touched a financial record, when, what the value was before and after, and why. It is not developer logging that happens to be persisted: it is the evidence the company produces when somebody outside asks whether its own control rules were actually followed. The \"why\" field is the one developers under-build and auditors read first.",
   v:"Vết kiểm toán — ghi lại ai sửa, lúc nào, từ giá trị nào sang giá trị nào, và vì sao. Đây là bằng chứng đưa ra khi bị thanh tra, không phải log cho lập trình viên.",
   r:"Two of them. transaction_histories (TM-06) stores changed_fields as {field:{old,new}} plus a snapshot of actor_name; identity-service · AuditLog is append-only — no setters, no updated_at, no version — and only BusinessAuditConsumer can write a row (SEC-04)."},
 butoandao:{w:"Reversal / adjusting entry — bút toán đảo, bút toán điều chỉnh",
   p:"The legal way to fix a posted entry: you do not change it, you post a second entry that cancels it or corrects the difference. Both rows stay in the books forever. A reversal undoes the whole entry so a correct one can be posted; an adjustment moves only the amount that was wrong.",
   v:"Bút toán đảo / điều chỉnh — sửa một bút toán đã ghi bằng cách ghi thêm một bút toán ngược lại hoặc chỉnh phần chênh, chứ không sửa bản ghi cũ. Cả hai dòng đều ở lại sổ.",
   r:"TransactionType.ADJUSTMENT — its javadoc calls it the only way to change an EXECUTED transaction, and TransactionStateMachine gives EXECUTED no outgoing transition at all. On the invoice side the same pair is AdjustmentKind = ADJUSTMENT | REPLACEMENT."},
 khoaso:{w:"Period close — khoá sổ",
   p:"At the end of a month, quarter or year the books for that period are frozen. The figures have been reported to somebody — an owner, a bank, the tax authority — and they must not move underneath the report afterwards. Corrections found later are still made, but they are dated into the period that is still open, not slipped back into the closed one.",
   v:"Khoá sổ — chốt số liệu của một kỳ sau khi đã báo cáo. Sai sót phát hiện sau đó vẫn sửa, nhưng ghi vào kỳ đang mở chứ không ghi ngược vào kỳ đã khoá.",
   r:"No general close module yet. The nearest thing shipped is BudgetStatus: LOCKED is a temporary freeze that reopens, CLOSED is \"hết kỳ / chốt sổ\" — a final state whose figures are frozen so periods can be compared (BM-11)."},
 luutru:{w:"Retention — lưu trữ tài liệu kế toán",
   p:"Accounting records must be kept, not merely recorded. Điều 41 Luật Kế toán 2015 sets the floor: at least ten years for the documents used directly to write the books and produce the annual financial statements, at least five for material used to run the business. Deleting a file to reclaim storage can therefore be the destruction of something the company is legally obliged to be able to produce.",
   v:"Lưu trữ — chứng từ dùng để ghi sổ và lập báo cáo tài chính năm phải giữ tối thiểu 10 năm (Điều 41 Luật Kế toán 2015). Xoá file cho nhẹ ổ đĩa có thể là huỷ thứ luật buộc phải xuất trình được.",
   r:"DocumentStatus.DELETED is a soft delete only — the object stays on MinIO for audit (SEC-04). Since 16/08/2026 no role at all, ADMIN included, holds a delete right over documents."},
 hosotindung:{w:"Credit profile (hồ sơ tín dụng)",
   p:"One row per partner holding everything the company has decided about lending to them: the ceiling granted, how much of it is taken up right now, what is left, the score, the grade, the risk level. There is exactly one per partner, and it is the row every other service asks before it lets an order through. Nothing in it is a fact about the partner — it is a record of decisions your own company made about the partner.",
   v:"Hồ sơ tín dụng — mỗi đối tác một dòng, giữ hạn mức đã cấp, phần đang chiếm dụng, phần còn lại, điểm và mức rủi ro. Đây là dòng mà mọi service khác phải hỏi trước khi cho một đơn hàng đi tiếp.",
   r:"credit-service · CreditProfile, table credit_profiles (CM-06). available_credit is a generated column, credit_limit − used_credit, computed by PostgreSQL — never recompute it by hand somewhere else. The only entity in this service carrying @Version, because two approvals for the same partner really do run at once."},
 tyleusudung:{w:"Credit utilisation (tỷ lệ sử dụng hạn mức)",
   p:"Outstanding exposure divided by the limit, as a percentage. It is the only one of the three limit numbers that means the same thing for a 50 million partner and a 5 billion one, which is why it is the number that belongs on the screen and in the alert. Ninety percent used is a warning whatever the size of the company.",
   v:"Tỷ lệ sử dụng hạn mức = dư nợ chia hạn mức. Đây là con số duy nhất so sánh được giữa đối tác nhỏ và đối tác lớn, nên nó mới là thứ nên hiện trên màn hình và trong cảnh báo.",
   r:"No column stores it — it is used_credit / credit_limit on CreditProfile, derived at read time. Storing a fourth number that has to agree with the other three is how they eventually stop agreeing."},
 chamdiemtindung:{w:"Credit scoring (chấm điểm tín dụng)",
   p:"Turning a partner's behaviour into a number from 0 to 100 by mixing five measured criteria, each with a weight and a conversion table. It runs again on every settled transaction, so the number moves under you while a user is looking at it. A score is evidence for a decision, never the decision itself.",
   v:"Chấm điểm tín dụng — quy hành vi của đối tác thành con số 0..100 từ năm tiêu chí, mỗi tiêu chí một trọng số và một thang quy đổi. Điểm chạy lại sau mỗi khoản tất toán, nên nó đổi ngay trong lúc người dùng đang nhìn.",
   r:"credit-service · CreditScoringRule (weights and bands live in the DB, total must be 100), ScoringCriterion, CreditScoreHistory (append-only), TriggerReason · CM-07, CM-08. A criterion with no measurement is dropped and the remaining weights normalised — CONTRACT_COMPLIANCE has no data source, so it is never scored."},
 xephangtindung:{w:"Credit grade (xếp hạng tín dụng)",
   p:"The letter the score is displayed as — AAA down to D. It exists so a human can read a partner in one glance instead of arguing about whether 71 is meaningfully better than 68. It drives nothing: the boundaries are hard-coded because no table holds them, and no rule in the system reads a letter.",
   v:"Xếp hạng tín dụng — chữ cái AAA đến D suy ra từ điểm, chỉ để người đọc nhìn một cái là hiểu. Nó không điều khiển gì cả; thứ điều khiển hành vi hệ thống là ngưỡng rủi ro.",
   r:"credit-service · CreditGrade enum, declared best to worst so compareTo works · CreditScoringEngine.calculateGrade (90/80/70/60/50/40/20). Deliberately not configurable — the ERD has no table for these boundaries."},
 nguongruiro:{w:"Risk threshold (ngưỡng rủi ro)",
   p:"One row per risk level saying what that level costs you: the highest exposure allowed, the lowest score that still counts as this level, how many days overdue is tolerated, and one action — warn, or block. Every company sets its own. It is the only place in the system that decides whether crossing a line stops an order or merely mentions it.",
   v:"Ngưỡng rủi ro — mỗi mức rủi ro một dòng: trần dư nợ, điểm tối thiểu, số ngày quá hạn chấp nhận được, và một hành động (cảnh báo hay chặn). Mỗi công ty tự đặt.",
   r:"credit-service · RiskThreshold, table risk_thresholds, UNIQUE (company_id, risk_level) · RiskLevel LOW/MEDIUM/HIGH/CRITICAL · ThresholdAction NOTIFY | BLOCK, only two values — CM-11, CM-12. No REQUIRE_APPROVAL here, unlike budget-service: the DDL CHECK would reject it in production."},
 hopdongtindung:{w:"Credit contract (hợp đồng hạn mức công nợ)",
   p:"The signed agreement the limit and the payment terms come from: the ceiling, the terms in days, the late-payment rate if one was agreed, a start date and an end date. Note the Vietnamese: this is a trading agreement between two companies, not a bank loan, so calling it hợp đồng tín dụng in the interface is a legal mistake. Its most dangerous day is the day it expires, because expiry is done by a nightly job rather than by anyone deciding.",
   v:"Hợp đồng hạn mức công nợ — nguồn của hạn mức và điều khoản thanh toán. Đừng gọi là \"hợp đồng tín dụng\" trên giao diện: đó là hợp đồng vay ngân hàng theo Luật Các TCTD, còn đây là tín dụng thương mại giữa hai doanh nghiệp.",
   r:"credit-service · CreditContract, ContractType (SUPPLIER_CREDIT, CUSTOMER_CREDIT, BANK_FACILITY), ContractTemplate with {{placeholder}} bodies, ContractStatus DRAFT → ACTIVE → EXPIRED | TERMINATED · CM-15..CM-18. There is no EXPIRING status: \"about to expire\" is derived, end_date − today ≤ notice_days, and the contract stays fully ACTIVE throughout."},
 tuoino:{w:"Aging report (báo cáo tuổi nợ)",
    p:"The total owed, broken into buckets by how far past its due date each piece is: in term, 1–30 days over, 31–60, 61–90, and over 90. One total tells you almost nothing — ten billion all from last fortnight is a healthy business, ten billion with a third of it past ninety days is a company about to write something off. The bucket boundaries are a company setting, not a caption, because different industries collapse at different speeds.",
    v:"Báo cáo tuổi nợ — chia tổng dư nợ theo số ngày quá hạn: trong hạn, 1–30, 31–60, 61–90, trên 90 ngày. Một con số tổng không nói lên điều gì; hình dáng của nó mới nói.",
    r:"credit-service · GET /credit/reports/aging → AgingReportResponse with [current, bucket1..3, over]. Boundaries come from credit_settings.aging_buckets (default [30,60,90]), and only OUTSTANDING and OVERDUE exposures are counted (CM-20)."},
  butrucongno:{w:"Offsetting (bù trừ công nợ)",
    p:"When a partner is both your customer and your supplier, the two debts can cancel each other instead of two payments being wired in opposite directions. No money moves and both obligations are legally extinguished — this is a payment made out of paper, not a tidy-up. The legal basis is Điều 378 Bộ luật Dân sự 2015, offsetting of obligations.",
    v:"Bù trừ công nợ — đối tác vừa nợ mình vừa được mình nợ thì hai khoản triệt tiêu nhau, không bên nào phải chuyển tiền. Căn cứ Điều 378 Bộ luật Dân sự 2015.",
    r:"credit_exposures.offset_amount grows line by line; when amount − offset_amount reaches 0 the exposure becomes SETTLED with settled_date = the date of the minutes. No new status and no new event — offsetting is the second road to settlement (CM-21)."},
  bienbanbutru:{w:"Offset minutes (biên bản bù trừ công nợ)",
    p:"The document both parties sign to record an offset: which debts on each side, how much of each, and the one total that is being cancelled. Three things make it lawful rather than convenient — same partner, same currency, and the two sides totalling exactly the same amount. An unbalanced minutes has no total, so there is nothing for either party to be agreeing to.",
    v:"Biên bản bù trừ công nợ — văn bản hai bên ký, ghi rõ khoản nào bù khoản nào và tổng bị triệt tiêu. Cùng đối tác, cùng loại tiền, tổng hai phía phải bằng nhau tuyệt đối.",
    r:"credit_offsets + credit_offset_lines (lines are append-only, no setters). OffsetStatus is CONFIRMED → CANCELED with no DRAFT. All five invariants are checked in CreditOffsetService.create and return 422 — no CHECK constraint can see across rows (CM-21)."},
  xoasono:{w:"Write-off (xoá sổ nợ)",
    p:"Admitting a debt will never be collected and taking it out of the live books. The money is given up; the record is not. The row stays with everything that led to it, because a write-off is a decision somebody made on a date and the row is the evidence of it. \"We finally deleted those old debts\" describes something else entirely, and something nobody was authorised to do.",
    v:"Xoá sổ nợ — chấp nhận không đòi được nữa. Mất tiền chứ không mất bản ghi: bản ghi vẫn nằm đó làm bằng chứng cho một quyết định có người chịu trách nhiệm.",
    r:"ExposureStatus.WRITTEN_OFF — the row is kept as audit trail (SEC-04). Not the same as a cancelled transaction, where the exposure row is deleted outright because the debt never came into existence; confuse the two and every partner with a cancelled transaction looks like a bad debtor."},
 laichamtra:{w:"Late-payment interest (lãi chậm trả)",
   p:"What a buyer owes on top of the invoice for having held the seller's money past the due date. It is not a fine and not a fee — it is the price of the days. Between two companies it runs under Điều 306 Luật Thương mại 2005, which sets no ceiling, and it accrues on the principal alone.",
   v:"Lãi chậm trả — tiền lãi trên số tiền bên mua giữ quá hạn. Theo Điều 306 Luật Thương mại 2005, không có trần, và chỉ tính trên nợ gốc.",
   r:"credit-service · credit_exposures.late_interest_accrued (CM-19). The nightly overdue job adds to it and never adds it into amount — interest on interest is nobody's agreement."},
 noigoc:{w:"Principal (nợ gốc)",
   p:"The original debt itself: the value of goods delivered or money advanced, before any penalty and before any damages. It is the one figure in a dispute that late-payment interest is allowed to accrue on. Every other money row attached to the same breach has to be kept where the interest routine cannot reach it.",
   v:"Nợ gốc — tiền hàng hoặc tiền ứng trước, chưa gồm phạt và bồi thường. Đây là số duy nhất được tính lãi chậm trả.",
   r:"credit-service · CreditExposure.amount, always > 0 (ck_credit_exposures_amount) with the sign carried by ExposureDirection. Nothing else in the exposure row is a base for interest."},
 phatvipham:{w:"Contractual penalty (phạt vi phạm)",
   p:"A sum the two sides agree in advance that the breaching party will pay, owed whether or not the breach cost anything. It exists only if the contract says so, and Điều 301 Luật Thương mại 2005 caps it at 8% of the value of the breached obligation. Late-payment interest may never be charged on it.",
   v:"Phạt vi phạm — khoản hai bên thoả thuận trước, chỉ có nếu hợp đồng ghi, trần 8% giá trị phần nghĩa vụ bị vi phạm (Điều 301 Luật Thương mại 2005). Không được tính lãi trên khoản này.",
   r:"No entity models it yet — the clause lives in the seeded contract templates, V3__seed_contract_templates.sql, whose test asserts they cite Điều 301 and never Điều 468 or Điều 266."},
 boithuong:{w:"Damages (bồi thường thiệt hại)",
   p:"Compensation for loss the injured party can actually prove — the extra cost of buying elsewhere, the contract lost downstream. Unlike a penalty it needs no clause, and unlike a penalty it has no percentage cap, because it is measured rather than agreed. Interest may not be charged on it either.",
   v:"Bồi thường thiệt hại — bù đắp thiệt hại thực tế chứng minh được, không cần điều khoản, không có trần %. Cũng không được tính lãi trên khoản này.",
   r:"Not modelled in sme-finance-scm either. Both this and phạt vi phạm sit outside CM-19 by design — the scope of the interest job is credit_exposures.amount and nothing else."},
 laisuatquahan:{w:"Overdue lending rate (lãi suất nợ quá hạn)",
   p:"The rate a bank charges on a loan that has gone past due, published and higher than its in-term rate. When a contract fixes no late-payment rate, Án lệ 09/2016/AL says to use the average of at least three banks in the locality, read at the time of payment — a number you look up and can show the source of, not a constant.",
   v:"Lãi suất nợ quá hạn — lãi ngân hàng áp cho khoản vay quá hạn. Không thoả thuận thì lấy trung bình của ít nhất ba ngân hàng tại địa phương ở thời điểm thanh toán.",
   r:"credit_contracts.late_interest_rate (nullable, no CHECK — deliberately) falls back to credit_settings.late_interest_rate, a versioned series keyed by effective_from so recomputing yesterday uses yesterday's rate."},
 anle:{w:"Precedent (án lệ)",
   p:"A published court decision that lower courts must follow. Vietnam has had them only since 2016 and there are few of them, so each one settles a question that used to be argued case by case. Read one the way you read an RFC: it names the inputs, states the rule, and — most usefully — records the alternative it rejected.",
   v:"Án lệ — bản án đã công bố mà toà cấp dưới bắt buộc theo. Đọc như đọc một RFC: có đầu vào, có quy tắc, và có cả cách tính đã bị bác.",
   r:"Án lệ số 09/2016/AL is cited in V3__seed_contract_templates.sql and in docs/design/06-state-machines.md §7; ContractTemplateSeedTest fails the build if a template stops citing it."},
 chuongtrinhtaitro:{w:"Financing programme (chương trình tài trợ)",
   p:"The framework agreement signed with one financier before any single invoice is financed: which product, how much in total, what percentage will be advanced, at what base rate, from when until when. Individual requests are drawn against it and eat into its limit. The type of programme is what decides who is allowed to start a request in the first place — which is why it is chosen once, at the top, and never edited afterwards.",
   v:"Chương trình tài trợ — thoả thuận khung ký với một đơn vị tài trợ: loại sản phẩm, tổng hạn mức, tỷ lệ ứng trước, lãi cơ sở, thời hạn. Từng đề nghị tài trợ rút vào hạn mức của nó, và loại chương trình quyết định luôn ai được khởi tạo đề nghị.",
   r:"scf-service · FinancingProgram, table financing_programs · ProgramType = INVOICE_DISCOUNTING | REVERSE_FACTORING | INVENTORY_FINANCING, mapped updatable = false · ProgramStatus DRAFT → ACTIVE → SUSPENDED | CLOSED (SCF-06, SCF-09). The DDL deliberately carries no CHECK (used_limit <= total_limit): the check lives in the service with a compare-and-set, because a constraint there would block legitimate reversals."},
 denghitaitro:{w:"Financing request (đề nghị tài trợ)",
   p:"One request to turn one invoice into cash now — how much, over how many days, from which financier. Despite the English name it is not an offer made to you: it is the company's own application, and the financiers' answers arrive as quotes attached to it. One invoice may only have one of these alive at a time, or the same money would be sold twice.",
   v:"Đề nghị tài trợ — một yêu cầu ứng tiền trên một hoá đơn: bao nhiêu, kỳ hạn mấy ngày, hỏi đơn vị nào. Báo giá của các bên là câu trả lời gắn vào nó. Mỗi hoá đơn chỉ được có một đề nghị đang sống.",
   r:"scf-service · FinancingOffer, table financing_offers, offer_no as TT-{yyyy}-{seq} · OfferStatus DRAFT → SUBMITTED → QUOTED → ACCEPTED → DISBURSED → SETTLED, with REJECTED, EXPIRED, OVERDUE and DEFAULTED off the side (SCF-01, SCF-08). uk_offers_active_per_invoice is a partial unique index over five statuses, OVERDUE among them — a late loan still occupies its invoice."},
 giaingan:{w:"Disbursement (giải ngân)",
   p:"The day the financier actually moves the money. Everything before it is paperwork, and it is the only day in the whole flow on which the company's bank balance changes. What arrives is the advance minus the fee, never the face value of the invoice — the fee is taken off the top rather than billed later.",
   v:"Giải ngân — ngày đơn vị tài trợ thực sự chuyển tiền, và là ngày duy nhất trong cả luồng mà số dư tài khoản thay đổi. Số về là phần ứng trước trừ phí, không phải mệnh giá hoá đơn.",
   r:"OfferStatus.DISBURSED with FinancingOffer.disbursedAt · net_proceeds = requested_amount − fee_amount, held by ck_offers_net_proceeds. What must be proved first branches on factoring_product — three legal products, three different pieces of evidence (TT 20/2024/TT-NHNN Điều 14, disbursementGateSatisfied()). SCF-08."},
 hoantra:{w:"Repayment (hoàn trả)",
   p:"Giving the advance back. In the two invoice products the buyer does it, paying the financier directly on the invoice's original due date, and the company that received the cash never sends a đồng. In inventory financing the borrower repays on the loan's own schedule. Which of the two applies comes from the product, not from who received the money — and that is the sentence worth remembering.",
   v:"Hoàn trả — trả lại khoản đã ứng. Ở hai sản phẩm trên hoá đơn thì chính bên mua trả thẳng cho đơn vị tài trợ; ở tài trợ tồn kho thì người vay tự trả theo lịch của khoản vay. Ai trả là do sản phẩm quyết định, không phải do ai đã nhận tiền.",
   r:"scf-service · FinancingRepayment, table financing_repayments, one row per instalment and normally exactly one — factoring is a single short advance, not a loan in instalments · RepaymentStatus PENDING → PAID | OVERDUE (SCF-15). The last instalment turning PAID is what moves the offer to SETTLED, in the same transaction as mark-paid rather than in a nightly job."},
 taitrotonkho:{w:"Inventory financing (tài trợ hàng tồn kho)",
   p:"Borrowing against goods sitting in the warehouse, at a moment when nobody owes you anything at all. There is no invoice to sell, so what the lender prices is what it could get for those goods if it had to sell them itself — which is why only a fraction of the stated value is ever advanced, and why the value has to be re-checked rather than trusted.",
   v:"Tài trợ hàng tồn kho — vay trên hàng đang nằm trong kho, khi chưa ai nợ mình đồng nào. Không có hoá đơn để bán, nên thứ được định giá là số tiền ngân hàng thu được nếu phải tự đem hàng đi bán; vì thế chỉ ứng một phần giá trị và phải định giá lại định kỳ.",
   r:"ProgramType.INVENTORY_FINANCING over InventoryItem and CollateralPledge. The limit is Σ pledged_value of rows still PLEDGED × advance_rate (SCF-13), written once in PledgeService.maxFinancingAmount and reused by the disbursement guard. Falling under min_value_threshold publishes scf.collateral-below-threshold.v1 (SCF-14). InventoryStatus.PLEDGED does not freeze the goods — thế chấp hàng hoá luân chuyển, BLDS Điều 321 khoản 4."},
 baothanhtoan:{w:"Factoring (bao thanh toán)",
   p:"Selling a receivable to a bank or finance company, which pays most of it now and collects from the buyer later. In Vietnam this is the legal frame for every product that advances money against an invoice — a commercial invoice is not a negotiable instrument, so nothing on it can be \"discounted\" under the credit institutions law. Whatever the screen calls it, the contract underneath is a factoring contract.",
   v:"Bao thanh toán — bán khoản phải thu cho tổ chức tín dụng để lấy tiền trước. Ở Việt Nam mọi sản phẩm ứng vốn trên hoá đơn về pháp lý đều là bao thanh toán, dù giao diện có gọi là \"chiết khấu hoá đơn\".",
   r:"scf-service · FactoringProduct on financing_offers.factoring_product, three values from TT 20/2024/TT-NHNN Điều 3 khoản 9–11. Do not confuse it with ProgramType, which is the commercial programme the company signed."},
 truydoi:{w:"Recourse (truy đòi)",
   p:"The financier's right to come back to the seller when the buyer does not pay. With recourse, the seller hands the advance back and is left holding a debt nobody is paying — so it sold the timing, not the risk. Without recourse, the financier absorbs the loss, and has priced for it. Vietnamese law does not use the word truy đòi at all: it speaks of the seller's cam kết hoàn trả, an undertaking to repay.",
   v:"Truy đòi — quyền của đơn vị tài trợ đòi lại tiền từ bên bán khi bên mua không trả. Có truy đòi nghĩa là bên bán chỉ bán được thời gian, chứ rủi ro vẫn của mình. Luật gọi đây là cam kết hoàn trả của bên bán.",
   r:"Not a boolean. FactoringProduct.SELLER_WITH_RECOURSE vs SELLER_WITHOUT_RECOURSE vs BUYER — the enum also decides what evidence unlocks disbursement (FinancingOffer.disbursementGateSatisfied, 06 §6.2) and who the financier's customer is."},
 taisandambao:{w:"Collateral / security (tài sản bảo đảm)",
   p:"Something the lender can sell if the borrower does not repay. In this system it is a batch of stock pledged against a financing offer. Pledged does not mean frozen: the law treats stock as revolving collateral, so the borrower goes on selling it in the ordinary course of business — the control is periodic revaluation against an agreed floor, not a lock on each batch.",
   v:"Tài sản bảo đảm — thứ bên cho vay có thể bán khi bên vay không trả được. Thế chấp hàng hoá luân chuyển (BLDS Đ.321 khoản 4) nên hàng vẫn được bán bình thường; kiểm soát bằng định giá lại và ngưỡng giá trị, không phải khoá từng lô.",
   r:"scf-service · CollateralPledge (status PLEDGED → RELEASED | LIQUIDATED) over an InventoryItem, SCF-11. Registering the security at the national registry is voluntary for movable assets (NĐ 99/2022/NĐ-CP) — a blank registration_no only costs priority against third parties, so the system warns and does not block."},
 tyleungtruoc:{w:"Advance rate / loan-to-value (tỷ lệ ứng trước)",
   p:"The share of an asset's value a financier will actually put up: sixty percent against ten billion of stock is a six billion facility. It is never a hundred, because the value on the shelf and the value in a forced sale are two different numbers and the lender is planning for the second one. The rest is the lender's margin of error, and on a factored invoice the un-advanced slice is held back as a reserve until settlement.",
   v:"Tỷ lệ ứng trước — phần trăm giá trị tài sản mà bên tài trợ chịu ứng. Không bao giờ 100%, vì giá trên kệ và giá bán tháo là hai con số khác nhau; phần chênh là biên an toàn của bên cho vay.",
   r:"financing_offers.advance_rate — one column doing two jobs. It sets the amount disbursed (the remainder is the reserve, 06 §6), and it is also the multiplier in the SCF-13 collateral limit: PledgeService.maxFinancingAmount = Σ pledged_value × advance_rate."},
 dinhgiataisan:{w:"Revaluation (định giá lại tài sản bảo đảm)",
   p:"Putting a fresh price on pledged stock, on a dated record somebody is answerable for. It is the least glamorous job in the module and the one that moves the most money: every revaluation silently rewrites the financing limit the pledge supports, so a price the market moved can put a borrower over a ceiling it never touched.",
   v:"Định giá lại tài sản bảo đảm — gán giá mới cho hàng đang thế chấp, có ngày và có người chịu trách nhiệm. Mỗi lần định giá lại là một lần hạn mức tài trợ thay đổi, dù bên vay không làm gì cả.",
   r:"InventoryItem.revalue(quantity, unitValue, valuationDate) — total_value is derived, never typed in, or SCF-14 compares against a number nobody computed. PledgeService.syncAfterRevaluation then rewrites pledged_value and publishes smefin.scf.collateral-below-threshold.v1 on the crossing only."},
 nhataitro:{w:"Finance provider (đơn vị tài trợ)",
   p:"The institution that actually puts up the money — a commercial bank, a general finance company, a factoring company, a foreign bank branch. Only a licensed credit institution may disburse a factoring advance in Vietnam, so a row in the marketplace catalogue is a contact, not a licence. Each provider registers the band of rates it is prepared to quote inside, and that band is the only thing the system may build an estimate from.",
   v:"Đơn vị tài trợ — bên bỏ tiền ra. Chỉ tổ chức tín dụng mới được giải ngân bao thanh toán (Luật Các TCTD 32/2024; TT 20/2024 Điều 2), nên một bản ghi trong marketplace chỉ là đầu mối, không phải giấy phép.",
   r:"scf-service · FinanceProvider (finance_providers), ProviderStatus = ACTIVE | INACTIVE | SUSPENDED — only ACTIVE is asked for a price. min_rate/max_rate are the sole source of an ESTIMATED quote; there is no rating column, it was dropped in V4 because nothing ever filled it (SCF-16, SCF-19)."},
 chaogia:{w:"Quote (báo giá)",
   p:"One provider's answer to one financing request: a rate, a fee in đồng, the amount that would actually land in the account, the number of days, and the moment the price stops being good. A quote is a price with an expiry date, not a rate card — and unlike the system's own estimate, it is the number somebody is willing to sign.",
   v:"Báo giá — câu trả lời của một đơn vị tài trợ cho một đề nghị: lãi suất, phí, số tiền thực nhận, kỳ hạn, hạn hiệu lực. Đây mới là con số có giá trị pháp lý, không phải công thức ước tính trong hệ thống.",
   r:"ProviderQuote (provider_quotes): discount_rate, fee_amount, net_proceeds, tenor_days, valid_until, terms (jsonb), rank_no, status = RECEIVED | SELECTED | DECLINED | EXPIRED. UNIQUE (offer_id, provider_id) — one price per provider per request (SCF-17)."},
 laisuatthucte:{w:"Effective annual rate (lãi suất thực tế)",
   p:"Every cost of the deal added together, divided by the money that actually reached the account, then scaled up to a year over the days the money is genuinely held. It is the only unit in which two differently-worded offers can be compared, and it is almost never the number printed on the offer.",
   v:"Lãi suất thực tế quy năm — tổng chi phí chia cho số tiền thực nhận, quy về một năm theo đúng số ngày dùng tiền. Đây là đơn vị duy nhất so sánh được hai báo giá viết bằng hai kiểu khác nhau.",
   r:"FinancingFormula.effectiveAnnualRatePercent — fee × 36 500 ÷ (requested × tenor), a 365-day year. It is returned by POST /offers/{id}/calculate and by nothing else: MarketplaceCompareResponse.Option carries discount_rate, fee_amount and net_proceeds, and no effective rate at all (SCF-02, SCF-17)."},
 phithuxep:{w:"Arrangement fee (phí thu xếp)",
   p:"A one-off charge for opening the facility, quoted as a percentage of the amount and taken out of the money at drawdown. It is not interest, it does not grow with the number of days, and it is quoted apart from the rate — which is precisely why it falls out of comparisons. It belongs in the numerator with everything else the deal costs.",
   v:"Phí thu xếp — khoản thu một lần khi mở khoản tài trợ, tính theo % số tiền, trừ thẳng lúc giải ngân. Không phải lãi, không theo số ngày, nhưng vẫn phải cộng vào tổng chi phí khi so sánh.",
   r:"No column of its own. fee_amount holds the single number a provider chose to report, and the fee structure behind it belongs in ProviderQuote.terms (jsonb) — which no code path in scf-service currently writes, so it is {} on every row."},
 chietkhauthanhtoansom:{w:"Early-payment discount (chiết khấu thanh toán sớm)",
   p:"Money off the invoice for paying before the agreed date. \"2/10 net 30\" means two percent off if you pay on day ten instead of day thirty. Read as a discount it looks trivial; read as a return on the twenty days of cash you gave up, it is about 37% a year, and it beats every financing rate a marketplace will show you.",
   v:"Chiết khấu thanh toán sớm — bên bán giảm giá nếu trả trước hạn. \"2/10 net 30\" là giảm 2% khi trả ngày thứ 10 thay vì ngày thứ 30; quy ra năm khoảng 37%/năm, cao hơn mọi lãi suất tài trợ trên bảng so sánh.",
   r:"Not modelled — financing_offers price money coming in from a provider, not a discount taken from a supplier. Taking one shortens DPO, so it reaches the system through PaymentSchedule (CF-15) and cash_flow_metrics.dpo_days."},
 ngansach:{w:"Budget (ngân sách)",
   p:"A company deciding in advance how much a department, project or category may spend in a period — and then holding people to it. It is permission, not prediction: a forecast says what will probably happen, a budget says what is allowed to happen. That is why the number does not move when reality disagrees with it; somebody has to change it on purpose.",
   v:"Ngân sách — quyết định trước rằng một phòng ban, dự án hay danh mục được chi bao nhiêu trong kỳ. Là sự cho phép, không phải dự báo: dự báo nói điều sắp xảy ra, ngân sách nói điều được phép xảy ra.",
   r:"budget-service · Budget, table budgets. scope_type = COMPANY | DEPARTMENT | PROJECT | CATEGORY (BM-01), period_type = MONTHLY | QUARTERLY | ANNUAL (BM-02), status DRAFT → PENDING_APPROVAL → ACTIVE → LOCKED → CLOSED. Only ACTIVE takes part in the spending check."},
 phanbo:{w:"Allocation (phân bổ ngân sách)",
   p:"Cutting one line's plan across the periods of the year, so that spending a whole quarter's money in January is visible as a problem rather than as ordinary progress. Either split evenly, or given period by period when the money is genuinely lumpy — a trade fair in March is not one twelfth per month.",
   v:"Phân bổ ngân sách — chia kế hoạch của một dòng ra từng kỳ, chia đều hoặc theo lịch cụ thể. Nhờ vậy tiêu hết tiền cả quý ngay trong tháng đầu mới nhìn ra là bất thường.",
   r:"BudgetAllocation, table budget_allocations, AllocationMode = EVEN | MANUAL (BM-03). The sum of allocated_amount for a line must equal that line's planned_amount — enforced in BudgetAllocationService, not by a CHECK, because it spans two tables."},
 camket:{w:"Commitment (cam kết ngân sách)",
   p:"Money that has been approved but not yet paid. A purchase order signed on Monday is gone even though the bank balance has not moved — the company is contractually obliged and the budget must already know. This is the state everybody forgets, and forgetting it is how two spends that each fit are approved on the same afternoon and together do not.",
   v:"Cam kết ngân sách — tiền đã được duyệt nhưng chưa chi. Đơn hàng ký hôm thứ hai là tiền đã mất, dù số dư ngân hàng chưa động. Quên trạng thái này là lý do hai khoản chi cùng được duyệt rồi cùng vượt hạn mức.",
   r:"BudgetCommitment, table budget_commitments, CommitmentStatus = COMMITTED | CONSUMED | RELEASED (BM-10), held on budget_lines.committed_amount. UNIQUE (budget_line_id, transaction_id) is the last line of defence against a redelivered Kafka event committing the same money twice."},
 thucchi:{w:"Actual spend (thực chi)",
   p:"Money that has genuinely left the account against this budget line. It arrives late in the story: a spend is planned, then committed at approval, and only becomes actual on the day the payment executes. A budget report that shows actual alone is showing you the past, several weeks after the decisions that produced it were made.",
   v:"Thực chi — tiền đã thật sự rời khỏi tài khoản cho dòng ngân sách này. Chỉ ghi nhận vào ngày thanh toán chạy, tức là sau quyết định chi vài tuần.",
   r:"budget_lines.actual_amount (BM-06, BM-08). Written when transaction.executed arrives: the commitment moves COMMITTED → CONSUMED, committed_amount goes down and actual_amount goes up by the same figure — total used does not change at that moment."},
 chenhlech:{w:"Variance (chênh lệch ngân sách)",
   p:"The gap between what was allowed and what has been used, reported at the end of a period and watched during it. Positive means money left unspent; negative means the line is over. The interesting question is never the size of the gap but its cause — a cheaper supplier and a project that never started produce the same number and mean opposite things.",
   v:"Chênh lệch ngân sách — khoảng cách giữa kế hoạch và số đã dùng. Dương là còn dư, âm là đã vượt. Điều đáng hỏi không phải độ lớn của chênh lệch mà nguyên nhân của nó.",
   r:"BudgetUtilizationRow.varianceAmount (BM-11) = planned − (committed + actual) — note that commitments are subtracted, so the field carries exactly the same value as availableAmount beside it, and both are the generated column budget_lines.available_amount."},
 dubaodongtien:{w:"Cash forecast (dự báo dòng tiền)",
   p:"The projected balance of the bank account on each future day or week, built by laying the obligations that already exist on a calendar and adding them up. It is mostly an inventory, not a prediction: next quarter's payroll, rent, loan instalments and invoice due dates are all knowable today. The statistical part is the small residue nobody has a document for.",
   v:"Dự báo dòng tiền — số dư dự kiến của tài khoản theo từng ngày hoặc từng kỳ, dựng từ những nghĩa vụ đã tồn tại sẵn chứ không phải từ một mô hình thống kê. Lương, thuê mặt bằng, trả nợ vay, hạn hoá đơn: hôm nay đã biết hết.",
   r:"cashflow-service · ForecastRun (one execution) + CashFlowForecast (one row per period, with projected_inflow, projected_outflow, projected_closing and confidence_level). ForecastMethod has exactly three values — HISTORICAL_AVG, SCHEDULED_ONLY, HYBRID (CF-10). projected_closing is allowed to be negative on purpose: clamp it at zero and the only thing worth warning about disappears."},
 kichban:{w:"Scenario (kịch bản dự báo)",
   p:"The same obligations run again under one changed assumption — the largest customer pays thirty days late, a financing offer is declined, an order lands. The point is not to guess which one happens. It is to find out which single assumption the company's survival is resting on, so somebody can go and watch that one thing.",
   v:"Kịch bản — vẫn từng ấy nghĩa vụ, chạy lại với một giả định khác. Mục đích không phải đoán đúng, mà là tìm ra công ty đang sống nhờ giả định nào để có người canh chừng đúng chỗ đó.",
   r:"cashflow-service · ForecastScenario, table forecast_scenarios (CF-12). Exactly one is_baseline = true per company, guarded by the partial unique index uk_forecast_scenarios_baseline — promoting another baseline must demote the old one in the same transaction or PostgreSQL rejects both. assumptions is free-form JSONB, but the calculator understands only four keys: revenueGrowthPct, paymentDelayDays, costInflationPct, collectionRatePct. Unknown keys are kept, never dropped."},
 nguongcanhbao:{w:"Alert threshold (ngưỡng cảnh báo)",
   p:"The balance below which the system raises a cash alert. It is a design decision with a measurable cost on each side: set it too low and the first alert arrives on the day the account is already empty, set it too high and it fires most weeks until people stop opening the mail. The right question is not what number is correct but how many alerts a person will actually read in a month.",
   v:"Ngưỡng cảnh báo — mức số dư mà dưới đó hệ thống báo động. Đặt thấp quá thì cảnh báo đầu tiên đến đúng hôm đã hết tiền; đặt cao quá thì tuần nào cũng kêu và không ai đọc nữa. Câu hỏi đúng là một người sẽ đọc được bao nhiêu cảnh báo mỗi tháng.",
   r:"cashflow-service · cashflow_settings holds three of them — shortfall_threshold_amount (NOT NULL), low_balance_threshold_amount and large_outflow_threshold_amount. The last two being null means that alert type is switched off; writing 0 instead switches it on at zero, which is the opposite thing. cash_alerts.threshold_amount is only a snapshot of the value used for one alert, so changing the setting later still explains the old ones (CF-11)."},
 lichthanhtoan:{w:"Payment schedule (lịch thanh toán)",
   p:"A dated line saying that this much money is due to move on that day, generated from the terms agreed with a supplier or a customer rather than typed in by anyone. It is the backbone of a forecast: most of what happens next quarter is already sitting in these rows, waiting for its date.",
   v:"Lịch thanh toán — dòng ghi rõ ngày nào phải chuyển bao nhiêu, sinh ra từ điều khoản đã thoả thuận chứ không do ai gõ tay. Phần lớn dòng tiền quý tới đã nằm sẵn ở đây.",
   r:"cashflow-service · PaymentSchedule, table payment_schedules (CF-15). ScheduleStatus SCHEDULED → GENERATED | CANCELED, both final. direction is mandatory and cannot be derived from partner_id, because the same partner can be on both sides. The nightly job does not create the transaction itself — it publishes cashflow.payment-schedule-due.v1 and transaction-service creates it."},
 giaodichdinhky:{w:"Recurring transaction template (giao dịch định kỳ)",
   p:"A stamp that mints the same payment again every month, quarter or year: rent, payroll, social insurance, the licence fee. Recurring costs are the least glamorous input to a forecast and the most reliable one, because the amount barely moves and the date does not move at all.",
   v:"Giao dịch định kỳ — khuôn sinh lại cùng một khoản chi theo tháng, quý hoặc năm: thuê mặt bằng, lương, BHXH, lệ phí môn bài. Nhàm chán nhưng là đầu vào chắc chắn nhất của dự báo.",
   r:"transaction-service · RecurringTemplate with RecurringFrequency DAILY..YEARLY and RecurringStatus ACTIVE → PAUSED → COMPLETED (TM-02). nextRun counts from the anchor date, not from the last date generated — count from the last one and a template anchored on the 31st drifts to the 28th forever after its first February."},
 batkiemnhiem:{w:"Segregation of duties (nguyên tắc bất kiêm nhiệm)",
   p:"Keeping the person who records money apart from the person who holds it, so that faking the trail needs more than one person to agree. In Vietnamese law this is not a general duty to split roles — it is a closed list of forbidden pairs (Luật Kế toán 2015 Điều 52, Nghị định 174/2016/NĐ-CP Điều 19) plus a duty on the company to write internal control rules of its own (Điều 39 khoản 2, Thông tư 99/2025/TT-BTC Điều 3 khoản 2). Anything outside that list is your product's choice, and Nghị định 174/2016 Điều 18 khoản 1 says so explicitly.",
   v:"Bất kiêm nhiệm — tách người ghi sổ khỏi người giữ tiền. Luật chỉ cấm một danh sách đóng các cặp vai, ngoài danh sách đó là quyết định của sản phẩm chứ không phải nghĩa vụ luật định.",
   r:"masterdata-service derives segregationExempt in InternalControlPolicyResponse; transaction-service enforces it in requireExecutorNotMaker and requireExecutorNotApprover before a transaction may become EXECUTED (SEC-08, SEC-09)."},
 ketoantruong:{w:"Chief accountant (kế toán trưởng)",
   p:"The person legally answerable for a company's accounting — a statutory job title with qualification requirements, not a seniority label. Điều 19 khoản 3 Luật Kế toán 2015 requires their signature, or that of a person they authorised, on every spending voucher before the money moves. Thông tư 99/2025/TT-BTC Điều 10 khoản 4 forbids them signing in the manager's slot as well, so the two signatures on a payment have to be two people.",
   v:"Kế toán trưởng — người chịu trách nhiệm về công tác kế toán, có tiêu chuẩn luật định. Chứng từ chi tiền phải có chữ ký của kế toán trưởng (hoặc người được uỷ quyền) trước khi thực hiện.",
   r:"Roles.CHIEF_ACCOUNTANT, seeded as 'Kế toán trưởng' in V3__seed_roles_chief_accountant_cashier.sql. The step is UserTask_ChiefAccountant in payment-approval.bpmn, candidate group chief-accountant."},
 phutrachketoan:{w:"Person in charge of accounting (phụ trách kế toán)",
   p:"What a company may appoint instead of a chief accountant. For a micro-enterprise this is permanent rather than a stopgap — Nghị định 174/2016/NĐ-CP Điều 20 khoản 2 điểm b — and Thông tư 58/2026/TT-BTC Điều 3 khoản 2, in force from 01/7/2026, lets that person sign wherever a chief accountant would. A workflow step that blocks on the chief-accountant title therefore hangs forever at a company that lawfully has no such title.",
   v:"Phụ trách kế toán — người được bố trí thay kế toán trưởng. Doanh nghiệp siêu nhỏ được bố trí vĩnh viễn, và người này được ký thay kế toán trưởng trên chứng từ.",
   r:"No role of its own: the micro branch removes the step from the model instead. payment-approval-micro.bpmn has no UserTask_ChiefAccountant, and ChiefAccountantStep.isPresentIn() reads that off the deployed BPMN rather than off configuration (SEC-09)."},
 quymodoanhnghiep:{w:"Enterprise size (quy mô doanh nghiệp)",
   p:"A legal classification under Nghị định 80/2021/NĐ-CP Điều 5, not an adjective. Three tiers — siêu nhỏ, nhỏ, vừa — decided by the average annual social-insurance headcount as a precondition, then by revenue OR capital, with different thresholds for agriculture, industry and construction than for trade and services. It is the input that unlocks several exemptions, which is why declaring it falsely to win a support policy is an offence with restitution attached.",
   v:"Quy mô doanh nghiệp — phân loại pháp lý theo Điều 5 Nghị định 80/2021: lao động BHXH bình quân năm là điều kiện tiên quyết, sau đó xét doanh thu hoặc nguồn vốn, ngưỡng khác nhau theo lĩnh vực.",
   r:"masterdata-service · companies.enterprise_scale, CHECK IN ('MICRO','SMALL','MEDIUM'), NOT NULL DEFAULT 'MEDIUM' — the default is the strict end. Enum EnterpriseScale; every change appends a row to company_legal_profile_histories."},
 uyquyen:{w:"Time-boxed delegation (uỷ quyền có thời hạn)",
   p:"Lending one person's authority to another for a stated period. Two branches here: standing in for an approver, so their pending tasks also appear in the delegate's queue, and granting exactly one named functional permission instead of a whole role. Both always carry a start date, an end date, a reason and a recorded grantor; both are revocable and both leave a trail. You may only give away authority you hold, and some authority may never travel this road at all.",
   v:"Uỷ quyền có thời hạn — giao quyền cho người khác trong một khoảng thời gian có ngày bắt đầu và ngày kết thúc, có lý do, có người cấp, thu hồi được và để lại vết kiểm toán.",
   r:"workflow-service · approval_delegations for the approval branch, identity-service · permission_grants for the functional branch (TM-14). Both carry CHECK (to_date >= from_date) and a CHECK that the grantor is not the recipient."},
 doichieu:{w:"Reconciliation (đối chiếu)",
   p:"Proving, line by line, that the company's own record of money and the bank's record of the same money say the same thing. It is not a report and not a tidy-up: it is a control. Anything left over at the end of it is either something the books are missing or money that moved without anybody recording it, and the second of those is how theft is found.",
   v:"Đối chiếu — chứng minh từng dòng rằng sổ của doanh nghiệp và sao kê của ngân hàng nói cùng một điều. Đây là một chốt kiểm soát, không phải một báo cáo: thứ còn lại sau khi đối chiếu mới là thứ đáng đọc.",
   r:"transaction-service · Reconciliation, table reconciliations — one row pairs exactly one transaction with exactly one bank_statement_lines row, UNIQUE (transaction_id, bank_statement_line_id). Both ends change state in the same DB transaction: match_status → MATCHED and reconcile_status → MATCHED | DISPUTED (TM-10, CF-04). It publishes no event, deliberately: no money moves when you reconcile."},
 saoke:{w:"Bank statement (sao kê ngân hàng)",
   p:"The bank's own list of what happened in the account: a date, a value date, a signed amount, a free-text description, sometimes a counterparty name, sometimes a reference. There is no invoice number, no customer id, no order — nothing that joins to anything you own. It is the outside party's version of the truth, and it does not know your schema exists.",
   v:"Sao kê ngân hàng — bản ghi của phía ngân hàng: ngày, ngày giá trị, số tiền có dấu, diễn giải tự do, đôi khi có tên đối tác và số tham chiếu. Không có số hoá đơn, không có mã khách hàng — không có gì nối thẳng được vào dữ liệu của mình.",
   r:"transaction-service · BankStatementLine, table bank_statement_lines. The only place in the system where amount is negative — negative is money out — while transactions.amount is always positive with the direction in type, so every comparison takes the absolute value first. Formats: StatementFormat = CSV | XLSX | MT940, plus a bank API path (INT-03)."},
 khoplenh:{w:"Auto-matching (khớp tự động)",
   p:"Letting the machine pair statement lines with book entries by rule rather than by hand. Exact amount plus exact reference is safe. Exact amount alone is a guess. Matching on words in the description is a guess wearing the clothes of a fact. The safest rule is the one that refuses: a line is paired only when exactly one candidate qualifies, and that candidate is not also the only candidate of another line.",
   v:"Khớp tự động — để máy ghép dòng sao kê với bút toán theo luật. Đúng số tiền và đúng số tham chiếu thì an toàn; chỉ đúng số tiền là phỏng đoán; khớp theo chữ trong diễn giải là phỏng đoán đội lốt sự thật. Nhập nhằng thì không khớp.",
   r:"transaction-service · AutoMatcher — pure logic, no DB, six conditions, and \"ambiguous in either direction means no match\". MatchType = AUTO | MANUAL; an AUTO row leaves matched_by null. Everything it will not close comes back as MatchSuggestion[] with a reason naming the condition that failed. AutoMatchRequest no longer has a minConfidence: lowering one was the way to switch the unsafe path back on."},
 ngayhieuluc:{w:"Value date (ngày giá trị)",
   p:"The day the money is genuinely available in the account, as against the day the bank booked the entry. They differ by a day or two often enough that a match on the exact date would fail on perfectly ordinary transfers — a payment sent on Friday afternoon shows a Monday value date. It is the date matching should compare, and the date a file most often leaves blank.",
   v:"Ngày giá trị — ngày tiền thực sự có hiệu lực trong tài khoản, khác ngày ngân hàng ghi sổ. Lệch một hai ngày là chuyện thường, nên luật khớp phải có dung sai ngày; và đây cũng là cột tệp sao kê hay bỏ trống nhất.",
   r:"bank_statement_lines.value_date. The DDL allows null; the import service never does — it copies statement_date in, because the duplicate key (account, value_date, amount, reference_no) compares on this column and a blank one lets the same file be imported twice unnoticed. Tolerance is smefin.transaction.reconcile-date-tolerance-days, default 3."},
 chenhlechdoichieu:{w:"Reconciliation difference (chênh lệch đối chiếu)",
   p:"The gap between what the books say moved and what the bank says moved, on a pair somebody matched anyway. Usually a transfer fee taken on the same booking, a rounding, or a rate you did not choose. The number itself is small and what it costs is not: once it is inside a matched pair it stops being anybody's line to explain, so it has to carry a name and a reason.",
   v:"Chênh lệch đối chiếu — phần lệch giữa số trên sổ và số trên sao kê của một cặp đã khớp. Thường là phí chuyển tiền, làm tròn hay tỷ giá. Số thì nhỏ, nhưng nằm im trong một cặp đã khớp thì không còn ai phải giải thích nó nữa.",
   r:"reconciliations.difference_amount, computed by the server as |transactions.amount − |bank_statement_lines.amount||. Above smefin.transaction.reconcile-dispute-threshold (default 0) the transaction goes DISPUTED and note becomes mandatory. Auto-match can never produce one: a non-zero difference only ever comes from a manual match, where a person signs for it."},
 baocaotaichinh:{w:"Financial statements (báo cáo tài chính)",
   p:"The bundle a company files once a year: a statement of financial position, a profit and loss statement, a cash flow statement and the notes. It is not a management report — it goes to the tax authority, to the bank and to anyone lending money, on a fixed deadline of ninety days after the year ends. When a lender asks a customer for \"BCTC\", this whole bundle is what they mean, and it is usually a PDF someone will forward to you.",
   v:"Báo cáo tài chính — bộ báo cáo nộp hằng năm: tình hình tài chính, kết quả kinh doanh, lưu chuyển tiền tệ và thuyết minh. Nộp trong 90 ngày kể từ ngày kết thúc năm tài chính.",
   r:"report-service produces exactly one of the four statutory forms: RPT_CASH_FLOW_STATEMENT_B03. The other six seeded definitions are management reports — thu chi, dòng tiền, ngân sách, công nợ, thuế, hiệu quả tài trợ — not the filed set (REP-02)."},
 baocaotinhhinhtaichinh:{w:"Statement of financial position (Báo cáo tình hình tài chính)",
   p:"Sheet one: a photograph, taken at one instant, of everything the company owns and everything it owes. Cash, receivables, stock and equipment on one side; suppliers, loans and the owners' stake on the other. The two sides are equal by construction — that is what \"balance\" ever meant. Note the name: Thông tư 99/2025/TT-BTC retired \"Bảng cân đối kế toán\" in favour of this wording, moving toward the IFRS term, so you will meet both names in the same codebase.",
   v:"Báo cáo tình hình tài chính — ảnh chụp tại một thời điểm: doanh nghiệp có gì và nợ ai. Thông tư 99/2025/TT-BTC đã bỏ tên cũ \"Bảng cân đối kế toán\", tiến gần cách gọi của IFRS.",
   r:"No report-service definition produces it. The only trace of it in the code is CashFlowMetricsCalculator citing B01-DN mã 110 — tiền và các khoản tương đương tiền — as the denominator of runway_days, which is why account_balances.account_type had to exclude CREDIT_LINE."},
 ketquakinhdoanh:{w:"Income statement (Báo cáo kết quả hoạt động kinh doanh)",
   p:"Sheet two: what the company earned across a stretch of time. Revenue at the top, cost of goods and overheads below it, profit at the bottom. Every warning in lesson 01 lives on this sheet — it books revenue on the day of delivery, so a company can be magnificently profitable here while the bank account is empty.",
   v:"Báo cáo kết quả hoạt động kinh doanh — doanh thu, chi phí và lợi nhuận của cả một kỳ. Ghi nhận theo ngày giao hàng, nên lãi trên sheet này không có nghĩa là có tiền.",
   r:"Not produced anywhere in this system, and RPT_INCOME_EXPENSE is not it despite the name: 'Báo cáo thu chi' reads /internal/v1/transactions/summary, so it counts money received and paid, not revenue earned. Two different sheets, one misleading code."},
 luuchuyentiente:{w:"Cash flow statement (Báo cáo lưu chuyển tiền tệ)",
   p:"Sheet three: where the cash actually went, split three ways. Operating is money the business earned by trading. Investing is money spent on or raised from things the company keeps. Financing is money borrowed or put in by owners. The totals of two companies can be identical while one is earning its cash and the other is borrowing it — that split is the entire value of the sheet.",
   v:"Báo cáo lưu chuyển tiền tệ — tiền thật đã đi đâu, chia ba: hoạt động kinh doanh, đầu tư, tài chính. Tổng giống nhau nhưng nguồn tiền khác nhau thì sức khoẻ khác hẳn.",
   r:"cashflow-service · CashFlowActivity = OPERATING | INVESTING | FINANCING, mã 20 · 30 · 40 of form B03-DN, copied onto cash_flow_entries from masterdata.categories at write time. Rendered by RPT_CASH_FLOW_STATEMENT_B03 with groupBy=ACTIVITY; the method parameter accepts DIRECT only, and returns 422 for INDIRECT because that method starts from profit before tax, a figure no service here holds."},
 hethongtaikhoan:{w:"Chart of accounts (hệ thống tài khoản kế toán)",
   p:"The numbered list every accounting entry has to be filed under — 131 for customer receivables, 331 for supplier payables, 156 for goods in stock. The financial statements are built by rolling those numbers up. Thông tư 99/2025/TT-BTC let companies design their own sub-accounts without asking the Ministry first, dropped accounts that got in the way of real-time processing such as TK 611 and TK 1562, and added TK 215 for biological assets — trees and livestock — which is what opens agricultural supply chains to software like this.",
   v:"Hệ thống tài khoản kế toán — danh mục tài khoản mà mọi bút toán phải ghi vào. Thông tư 99/2025 cho doanh nghiệp tự thiết kế tài khoản cấp 2, cấp 3, bỏ TK 611 và TK 1562, thêm TK 215 cho tài sản sinh học.",
   r:"This system has no chart of accounts. masterdata-service · Account is a flat list of bank accounts, cash tills and credit lines — no parent_id, no path, no level — and its javadoc says so out loud precisely because the word \"tài khoản\" invites the confusion."},
 chedoketoan:{w:"Accounting regime (chế độ kế toán)",
   p:"The set of rules deciding which document forms, which books and which financial statements one company must produce. It is an assignment made by law from facts about the company, not a preference the company picks. Vietnam replaced the whole thing across 2026: Thông tư 99/2025/TT-BTC from 01/01/2026 for small, medium and large enterprises, retiring Thông tư 200/2014/TT-BTC; Thông tư 58/2026/TT-BTC from 01/07/2026 for micro-enterprises and hộ kinh doanh, replacing Thông tư 132/2018/TT-BTC. The two pull in opposite directions, so which one a customer falls under changes what the product may render.",
   v:"Chế độ kế toán — bộ quy định về biểu mẫu chứng từ, sổ kế toán và báo cáo tài chính mà một doanh nghiệp phải làm. Từ 2026 có hai chế độ: Thông tư 99/2025 cho doanh nghiệp nhỏ, vừa, lớn và Thông tư 58/2026 cho doanh nghiệp siêu nhỏ và hộ kinh doanh.",
   r:"Not modelled. There is no AccountingRegime enum and no accounting_regime column anywhere in sme-finance-scm; Thông tư 99 and 58 appear only as javadoc citations (EnterpriseScale, V9__company_legal_profile.sql, ApprovalTaskService). The nearest derived-from-legal-profile mechanism is InternalControlPolicyResponse (SEC-09), and it gates approval steps, never reports."},
 khautru:{w:"VAT deduction method (phương pháp khấu trừ)",
   p:"Paying VAT on the difference: output VAT charged to customers minus input VAT paid to suppliers. It needs both sides of the tax tracked, which is why every regime that allows it also demands a book for it. The alternative is the direct method. Which one a company uses is the first of the two questions that decide its whole accounting regime under Thông tư 58/2026.",
   v:"Phương pháp khấu trừ — nộp thuế GTGT trên phần chênh lệch giữa thuế đầu ra và thuế đầu vào, nên phải theo dõi cả hai chiều.",
   r:"Not modelled as a method. masterdata-service has tax_rates with TaxType (VAT, PIT, CIT, WHT, OTHER) — rates, not methods (TM-08). The word \"khấu trừ\" appears in code only in the withholding-at-source sense in DocumentTaxType."},
 tinhtructiep:{w:"Direct VAT method (phương pháp trực tiếp)",
   p:"Paying VAT as a flat percentage of revenue, with no input tax deducted. Simpler and usually more expensive, and it is what most very small businesses use. Because there is no input side, there is nothing to reconcile — which is exactly why Thông tư 58/2026 gives companies on this method fewer books to keep.",
   v:"Phương pháp trực tiếp — nộp thuế GTGT theo tỷ lệ % trên doanh thu, không khấu trừ thuế đầu vào. Đơn giản hơn nên sổ sách cũng ít hơn.",
   r:"Not modelled. Nothing in the system records how a company pays VAT — only the rate on a transaction, in transaction_taxes (tax_type, tax_rate, taxable_amount, declare_status)."},
 sotheodoi:{w:"Accounting book (sổ kế toán, sổ theo dõi)",
   p:"Not a report you generate on demand — a named form with a code printed on it, which the state publishes and the company fills in. S1-DNSN is the revenue book; S3b-DNSN is the VAT-obligation book. A chứng từ is the evidence behind one line, a sổ is where the lines accumulate, and a báo cáo tài chính is the annual summary filed with the state. Three separate obligations, and a company can owe one without owing the others.",
   v:"Sổ kế toán — biểu mẫu có mã số do nhà nước ban hành, doanh nghiệp ghi vào, ví dụ S1-DNSN là sổ doanh thu. Khác với chứng từ (bằng chứng từng giao dịch) và khác với báo cáo tài chính (bản tổng hợp nộp hằng năm).",
   r:"Not modelled. report-service holds seven global report_definitions rows with no company_id — no book, no form code, no per-customer set (REP-01 to REP-06). The only statutory statement built is RPT_CASH_FLOW_STATEMENT_B03, and the template itself says mã 60 and 70 are still to come."},
 hokinhdoanh:{w:"Household business (hộ kinh doanh)",
   p:"A business registered to an individual or a family rather than incorporated as a company. It is the most common form of business in Vietnam and it is not a legal person, so much of company law simply does not reach it. Thông tư 58/2026/TT-BTC brings household businesses inside a formal accounting regime for the first time — which makes them a new customer population, with obligations that are smaller than a company's, not the same ones scaled down.",
   v:"Hộ kinh doanh — cơ sở kinh doanh do cá nhân hoặc hộ gia đình đăng ký, không phải pháp nhân. Thông tư 58/2026 lần đầu tiên đưa hộ kinh doanh vào một chế độ kế toán chính thức.",
   r:"Not modelled. LegalForm in masterdata-service is SOLE_PROPRIETORSHIP, LLC_SINGLE, LLC_MULTI, JSC, OTHER — a hộ kinh doanh lands in OTHER, which decides nothing. PartnerType is only SUPPLIER, CUSTOMER, BOTH. One code comment (credit-service MasterdataRefs) notes a household business may have no tax code."}
};
/* which lesson introduces each term */
window.TERM_LESSON = {};
Object.keys(window.TERMS).forEach(function(k){ window.TERM_LESSON[k] = window.TERMS[k].l || "01"; });
