/* Từ điển tài chính cho dân kỹ thuật. Mỗi bài học đều dùng chung bộ này, và thư viện tìm kiếm nó.
   w = thuật ngữ · p = giải thích đời thường · v = tên tiếng Anh · r = chỗ nó nằm trong code       */
window.TERMS = {
 dongtien:{w:"Dòng tiền (cash flow)",
   p:"Tiền thật sự đi vào và đi ra khỏi tài khoản, theo ngày nó thực sự chuyển. Không phải doanh thu, không phải lợi nhuận — chỉ là: hôm nay tài khoản dày lên hay mỏng đi bao nhiêu.",
   v:"Cash in and cash out, on the day the money actually moves. Not revenue, not profit.",
   r:"cashflow-service · CashFlowEntry với FlowDirection = IN | OUT. Mỗi bản ghi là một lần tiền thật sự nhúc nhích."},
 doanhthu:{w:"Doanh thu (revenue)",
   p:"Giá trị hàng đã bán, ghi vào sổ ngay lúc giao hàng và xuất hoá đơn — kể cả khi khách hẹn 45 ngày nữa mới trả. Đây là chỗ dân kỹ thuật hiểu sai nhiều nhất: bán được 360 triệu không có nghĩa là có 360 triệu trong tài khoản.",
   v:"Revenue is recognised when goods are delivered, not when the customer pays.",
   r:"Trong hệ thống, doanh thu sinh ra một Invoice ISSUED — chứ chưa sinh ra CashFlowEntry nào cả. Tiền chỉ xuất hiện khi có InvoicePayment."},
 loinhuan:{w:"Lợi nhuận (profit)",
   p:"Doanh thu trừ chi phí, tính trên sổ. Một công ty có thể lãi đều đặn suốt ba tháng mà vẫn không đủ tiền trả lương tháng thứ hai — vì lãi nằm trên giấy, còn lương thì phải trả bằng tiền mặt.",
   v:"Profit is an opinion, cash is a fact. A profitable company can still run out of money.",
   r:"Lợi nhuận không phải là một bảng trong hệ thống này — nó là kết quả tính ra ở report-service. Cái hệ thống theo dõi từng ngày là dòng tiền."},
 phaithu:{w:"Khoản phải thu (accounts receivable)",
   p:"Tiền khách đang nợ mình. Đã giao hàng, đã xuất hoá đơn, chưa nhận được tiền. Nó là tài sản trên sổ sách nhưng không tiêu được — bạn không trả lương nhân viên bằng khoản phải thu.",
   v:"Money customers owe you. An asset on paper that you cannot spend.",
   r:"Invoice.direction = RECEIVABLE, và bên credit-service là CreditExposure với ExposureDirection = RECEIVABLE."},
 phaitra:{w:"Khoản phải trả (accounts payable)",
   p:"Tiền mình đang nợ nhà cung cấp. Đã nhận hàng, chưa trả tiền. Nghe thì xấu nhưng thực ra là nguồn vốn miễn phí: mỗi ngày chưa phải trả là một ngày tiền còn nằm trong tài khoản của bạn.",
   v:"Money you owe suppliers — in practice, an interest-free loan from them.",
   r:"Invoice.direction = PAYABLE. Cùng một bảng invoices, chỉ khác một cột — nên đổi giá trị cột đó là đổi hẳn chiều sổ sách."},
 congno:{w:"Công nợ",
   p:"Từ tiếng Việt gộp cả hai chiều: phải thu và phải trả. Khi kế toán nói \"công nợ của đối tác A\", họ đang nói tới toàn bộ số dư còn treo giữa mình và A — có thể A vừa là khách hàng vừa là nhà cung cấp.",
   v:"Umbrella term for both receivables and payables with one partner.",
   r:"credit-service · CreditExposure. Một đối tác có thể có đồng thời exposure cả hai chiều — đó chính là tiền đề của nghiệp vụ bù trừ công nợ (CM-21)."},
 tonkho:{w:"Hàng tồn kho (inventory)",
   p:"Hàng đã mua, đã trả tiền, chưa bán được. Tiền của bạn đang nằm im trong kho dưới dạng thùng hộp. Kho càng đầy thì tiền mặt càng mỏng — đó là lý do \"bán chậm\" và \"hết tiền\" luôn đi cùng nhau.",
   v:"Goods you have paid for but not yet sold — cash frozen in a warehouse.",
   r:"scf-service · InventoryItem. Trong tài trợ hàng tồn kho, chính đống hàng này được đem thế chấp (CollateralPledge)."},
 vonluudong:{w:"Vốn lưu động (working capital)",
   p:"Số tiền một doanh nghiệp phải bỏ ra để giữ cho vòng quay kinh doanh chạy được: mua hàng, giữ kho, đợi khách trả tiền. Toàn bộ hệ thống này tồn tại để làm cho con số đó nhỏ lại.",
   v:"The money tied up keeping the business cycle turning.",
   r:"Không có bảng nào tên là vốn lưu động. Nó là tổng của ba thứ hệ thống có theo dõi: tồn kho + phải thu − phải trả."},
 dio:{w:"DIO — số ngày hàng nằm kho",
   p:"Trung bình hàng nằm trong kho bao nhiêu ngày trước khi bán được. Mua về ngày 1, bán ngày 21 thì DIO là 20.",
   v:"Days Inventory Outstanding — how long stock sits before it sells.",
   r:"cash_flow_metrics.dio_days, job hằng đêm ghi (CF-07)."},
 dso:{w:"DSO — số ngày khách trả tiền",
   p:"Trung bình bao nhiêu ngày từ lúc xuất hoá đơn đến lúc tiền thật sự về. DSO 45 nghĩa là mỗi đồng doanh thu phải chờ một tháng rưỡi mới thành tiền. DSO càng thấp càng khoẻ.",
   v:"Days Sales Outstanding — how long customers take to pay you.",
   r:"cash_flow_metrics.dso_days, tính từ dso_settled_count và dso_total_days (CM-03)."},
 dpo:{w:"DPO — số ngày mình trả nhà cung cấp",
   p:"Trung bình bao nhiêu ngày mình giữ được tiền trước khi phải trả nhà cung cấp. Đây là chỉ số duy nhất mà cao là tốt — nhưng kéo dài quá thì nhà cung cấp nghỉ chơi hoặc tăng giá.",
   v:"Days Payable Outstanding — how long you take to pay suppliers. Higher is better, up to a point.",
   r:"cash_flow_metrics.dpo_days (CM-03). Đề xuất điều khoản thanh toán tối ưu ở CM-04 chính là đi tối ưu con số này."},
 ccc:{w:"CCC — chu kỳ chuyển đổi tiền mặt",
   p:"Số ngày tiền của bạn rời khỏi tài khoản rồi mới quay về. Công thức: DIO + DSO − DPO. CCC bằng 35 nghĩa là mỗi vòng kinh doanh bạn phải tự bỏ tiền túi nuôi 35 ngày. Đây là con số quan trọng nhất trong bài 01.",
   v:"Cash Conversion Cycle = DIO + DSO − DPO. The days you finance the business yourself.",
   r:"cash_flow_metrics.ccc_days (CF-07). Ba cột kia là đầu vào của chính nó."},
 burnrate:{w:"Burn rate — tốc độ đốt tiền",
   p:"Mỗi tháng tài khoản mỏng đi bao nhiêu. Có hai loại và đừng nhầm: gross burn là tổng tiền chi ra mỗi tháng, net burn là phần thực sự hụt sau khi đã trừ tiền thu về.",
   v:"How much cash the company loses per month. Gross = all spending; net = spending minus income.",
   r:"cash_flow_metrics.burn_rate (net) và gross_burn_rate. Hai cột riêng vì trả lời hai câu hỏi khác nhau, không suy được cái này từ cái kia."},
 runway:{w:"Runway — số ngày cầm cự",
   p:"Với số tiền còn lại và tốc độ đốt hiện tại, còn bao nhiêu ngày nữa thì hết sạch. Đây là con số làm giám đốc mất ngủ, và là thứ mọi cảnh báo sớm trong hệ thống đang phục vụ.",
   v:"How many days of cash are left at the current burn rate.",
   r:"cash_flow_metrics.runway_days — null khi dòng tiền ròng dương, vì không cạn tiền thì không có \"số ngày cầm cự\"."},
 thanhkhoan:{w:"Thanh khoản (liquidity)",
   p:"Khả năng trả được các khoản đến hạn đúng lúc. Mất thanh khoản là chết — kể cả khi công ty đang có lãi và có cả kho hàng. Phá sản gần như luôn là chết vì thanh khoản, không phải chết vì lỗ.",
   v:"Being able to pay what is due, on the day it is due.",
   r:"CashAlert với CashAlertType cảnh báo thiếu hụt tiền mặt theo ngưỡng cấu hình (CF-11)."},
 hoadon:{w:"Hoá đơn (invoice)",
   p:"Chứng từ pháp lý ghi nhận một lần bán hàng: ai bán, ai mua, bao nhiêu tiền, hạn trả là ngày nào. Nó không phải là tiền, và cũng không phải là một dòng ghi chú tự do — nó là giấy tờ có hiệu lực pháp lý.",
   v:"The legal record of a sale, with a due date. Not money.",
   r:"scf-service · Invoice. Đáng chú ý: không có trạng thái OPEN (\"trong hạn / quá hạn\" suy từ due_date), và hoá đơn đã phát hành thì không huỷ được — Nghị định 70/2025 bỏ hẳn việc huỷ hoá đơn điện tử, sai thì phát hành hoá đơn thay thế (REPLACED)."},
 hanthanhtoan:{w:"Hạn thanh toán / điều khoản thanh toán",
   p:"Thoả thuận bao nhiêu ngày sau khi giao hàng thì khách phải trả. \"Net 45\" nghĩa là 45 ngày. Nghe như một trường ngày tháng bình thường, nhưng nó chính là cái quyết định DSO, và qua đó quyết định công ty sống hay chết.",
   v:"Payment terms — \"Net 45\" means the customer owes you in 45 days.",
   r:"Invoice.dueDate. Job đêm so due_date với hôm nay để chuyển hoá đơn sang OVERDUE — người dùng không tự bấm."},
 chietkhau:{w:"Chiết khấu hoá đơn (invoice discounting)",
   p:"Bán khoản phải thu của mình cho một đơn vị tài trợ để lấy tiền ngay, chịu mất một khoản phí. Đổi một phần lợi nhuận lấy thời gian. Với công ty đang kẹt tiền thì đó là một cuộc đổi chác rất đáng.",
   v:"Selling your receivable at a discount to get cash today instead of in 45 days.",
   r:"FinancingProgram với ProgramType = INVOICE_DISCOUNTING (SCF-01, SCF-02)."},
 taitronguocdong:{w:"Tài trợ ngược dòng (reverse factoring)",
   p:"Cùng ý tưởng, nhưng do bên mua đứng ra khởi xướng. Một tập đoàn lớn xác nhận \"hoá đơn này tôi chắc chắn trả\", nhờ đó nhà cung cấp nhỏ vay được theo uy tín của tập đoàn chứ không phải theo uy tín của chính mình — nên phí rẻ hơn hẳn.",
   v:"The buyer starts it: a small supplier borrows against the buyer's credit rating, not its own.",
   r:"ProgramType = REVERSE_FACTORING (SCF-06). Chiều hoá đơn ở đây là PAYABLE, ngược với chiết khấu hoá đơn."},
 duno:{w:"Dư nợ (exposure)",
   p:"Số tiền còn treo với một đối tác tại thời điểm này. Đây là từ mà kế toán dùng khi hỏi \"còn nợ bao nhiêu\", và là thứ mọi hạn mức, cảnh báo, báo cáo tuổi nợ đều đo.",
   v:"The amount currently outstanding with one partner.",
   r:"credit-service · CreditExposure, trạng thái OUTSTANDING → SETTLED / OVERDUE / WRITTEN_OFF."},
 hanmuc:{w:"Hạn mức (credit limit)",
   p:"Trần số tiền được phép nợ. Vượt trần thì hệ thống chặn hoặc bắt duyệt thêm cấp. Nó là một con số nghiệp vụ, không phải một ràng buộc kỹ thuật — nhưng nếu code sai thì công ty mất tiền thật.",
   v:"The ceiling on how much credit a partner may have outstanding.",
   r:"SupplierLimit bên scf-service (hạn mức tài trợ) và RiskThreshold bên credit-service (ngưỡng rủi ro, CM-11, CM-12)."}
};

/* bài học nào giới thiệu từ nào */
window.TERM_LESSON = {};
Object.keys(window.TERMS).forEach(function(k){ window.TERM_LESSON[k] = window.TERMS[k].l || "01"; });
