/* Shared glossary — every lesson taps the same terms, the library searches them.
   Third block says where the term shows up once the system is in production. */
window.TERMS = {
 functional:{w:"Functional requirement",
   p:"What the system does, as a sentence a user could say: shorten a link, redirect a visitor, show me my links. If it is a verb the product does, it belongs here.",
   v:"Yêu cầu chức năng — hệ thống làm gì, nói được thành câu người dùng nói: rút gọn link, chuyển hướng, xem link của tôi.",
   r:"The list of endpoints and screens. If a functional requirement has no endpoint and no job behind it, it was never built."},
 nonfunctional:{w:"Non-functional requirement",
   p:"How well the system has to do it, with a number: 99.9% up, a redirect in under 100 ms, five years of links kept. Without the number it is a wish, not a requirement.",
   v:"Yêu cầu phi chức năng — làm tốt đến mức nào, bắt buộc có con số: 99,9% sẵn sàng, chuyển hướng dưới 100 ms, giữ link 5 năm. Không có số thì chỉ là mong muốn.",
   r:"The SLO dashboard and the alert thresholds. A non-functional requirement nobody measures is one nobody meets."},
 qps:{w:"QPS (queries per second)",
   p:"How many requests arrive each second. The single number that decides whether one machine is enough, and it is always two numbers — reads and writes — because they cost different things.",
   v:"QPS — số request mỗi giây. Con số quyết định một máy có đủ không, và luôn là hai con số: đọc và ghi, vì chi phí khác nhau.",
   r:"The requests-per-second graph on the load balancer, split by route. Peak is usually two to three times the daily average."},
 estimate:{w:"Back-of-the-envelope estimate",
   p:"Arithmetic good to a factor of two or three, done in a minute, to find out which part of the design is the hard part. Users a day becomes requests a second becomes bytes a year. Precision is not the point; the order of magnitude is.",
   v:"Ước lượng nhanh — tính nhẩm sai số gấp đôi gấp ba cũng được, làm trong một phút, để biết phần nào của thiết kế là phần khó. Điểm quan trọng là bậc độ lớn, không phải độ chính xác.",
   r:"The capacity numbers in a design doc's first page — and the moment in an incident review when someone asks whether anyone ever did the maths."},
 rwratio:{w:"Read/write ratio",
   p:"How many reads happen for every write. A URL shortener is read a hundred times per link created; a logging system is the opposite. The ratio decides whether you optimise the path that stores or the path that serves.",
   v:"Tỷ lệ đọc/ghi — mỗi lần ghi có bao nhiêu lần đọc. Link rút gọn đọc gấp trăm lần tạo; hệ thống log thì ngược lại. Tỷ lệ này quyết định tối ưu đường lưu hay đường trả.",
   r:"Compare the GET and POST lines on the same traffic graph. If you have never looked, the ratio is probably not what the design assumed."},
 sketch:{w:"High-level design (the sketch)",
   p:"The first diagram: five to eight boxes and the arrows between them, drawn only after the requirements and the estimate exist. Every box should be able to say which number put it there.",
   v:"Thiết kế tổng thể — sơ đồ đầu tiên, năm đến tám ô và mũi tên, vẽ sau khi đã có yêu cầu và ước lượng. Mỗi ô phải nói được con số nào đặt nó vào đó.",
   r:"The architecture diagram on the team wiki — usually three boxes out of date, which is fine, as long as the arrows still tell the truth."},
 deepdive:{w:"Deep dive",
   p:"Going one level down on the single part of the sketch that is hard — the redirect path, the key generator, the click counter — and designing it properly: data model, failure cases, what happens at ten times the load.",
   v:"Đào sâu — xuống một tầng ở đúng phần khó nhất của sơ đồ và thiết kế cho tử tế: mô hình dữ liệu, trường hợp lỗi, chuyện gì xảy ra ở mười lần tải.",
   r:"The one component that has its own design doc, its own dashboard, and its own on-call runbook. Everything else got a paragraph."},
 tradeoff:{w:"Trade-off",
   p:"What you gave up to get what you chose, said out loud: a cache makes redirects fast and lets a deleted link keep working for a minute. A design with no stated trade-off has not been designed, it has been drawn.",
   v:"Đánh đổi — thứ bạn bỏ để lấy thứ bạn chọn, nói thành lời. Thiết kế không nêu được đánh đổi thì chưa phải thiết kế, mới chỉ là vẽ.",
   r:"The 'Alternatives considered' section of a design doc, and the sentence in the postmortem that begins 'we knew this could happen'."},
 bottleneck:{w:"Bottleneck",
   p:"The one component that is closest to its limit, and therefore the one that decides how much the whole system can do. Fixing anything else first is effort that changes nothing the user can feel.",
   v:"Nút thắt — thành phần gần giới hạn nhất, quyết định cả hệ thống làm được bao nhiêu. Sửa chỗ khác trước là công sức không đổi được gì người dùng cảm nhận.",
   r:"The resource sitting at 90% on the dashboard while everything else idles — nearly always the database, until it is the thing in front of the database."},
 latency:{w:"Latency",
   p:"How long one request takes, measured from the user's side. Quoted as a percentile — p50 is the typical case, p99 is the one in a hundred that is slow — because the average hides the users who are about to leave.",
   v:"Độ trễ — một request mất bao lâu, đo từ phía người dùng. Nêu theo phân vị — p50 là trường hợp thường, p99 là một trên trăm bị chậm — vì trung bình che mất những người sắp bỏ đi.",
   r:"The p99 line on the latency graph, and the timeout values in every client that calls you."},
 throughput:{w:"Throughput",
   p:"How much work the system completes per second — requests, messages, bytes. Latency is how long one thing takes; throughput is how many things get done. You can raise one and worsen the other.",
   v:"Thông lượng — hệ thống hoàn thành bao nhiêu việc mỗi giây. Độ trễ là một việc mất bao lâu; thông lượng là làm được bao nhiêu việc. Tăng cái này có thể làm xấu cái kia.",
   r:"Requests per second served, messages per second consumed — the number that autoscaling rules are written against."},
 availability:{w:"Availability",
   p:"The share of time the system answers correctly, written as nines: 99.9% is about nine hours down a year, 99.99% is under an hour. Each extra nine costs roughly ten times more than the last.",
   v:"Độ sẵn sàng — tỷ lệ thời gian hệ thống trả lời đúng, viết theo số chín: 99,9% là khoảng 9 giờ chết mỗi năm, 99,99% là dưới 1 giờ. Mỗi số chín thêm tốn gấp khoảng mười lần.",
   r:"The uptime figure in the SLA, and the error budget the team is or is not allowed to spend on risky deploys this month."},
 rtt:{w:"Round trip time (RTT)",
   p:"How long a packet takes to go from you to the other machine and back. Inside a datacenter it is a fraction of a millisecond; across a city a few; across a region tens; across an ocean well over a hundred. Every handshake costs at least one.",
   v:"Thời gian một gói tin đi và về. Trong một trung tâm dữ liệu là dưới một mili giây; trong thành phố vài ms; trong khu vực vài chục; xuyên đại dương hơn một trăm. Mỗi lần bắt tay tốn ít nhất một RTT.",
   r:"The ping to your own load balancer from the user's country. Nothing in the code can lower it — only distance and fewer trips can."},
 dns:{w:"DNS lookup",
   p:"Turning a name into an address before anything else can happen. A cold lookup goes out to a resolver and can cost tens of milliseconds; a cached one costs nothing. It is the first hop of the first request, and it is invisible in server logs because it happens before the server hears anything.",
   v:"Đổi tên miền thành địa chỉ trước khi làm bất cứ gì. Lần đầu (chưa cache) mất vài chục ms; lần sau gần như không. Đây là hop đầu tiên và server không thấy nó trong log.",
   r:"The first bar in the browser's network waterfall — and the one your own monitoring never sees."},
 tlshandshake:{w:"TLS handshake",
   p:"Agreeing on the keys that encrypt the connection. TLS 1.3 does it in one round trip, TLS 1.2 in two, and a resumed session in zero. On a cold connection across an ocean this alone is over a hundred milliseconds of nothing the user can see.",
   v:"Thoả thuận khoá mã hoá cho kết nối. TLS 1.3 tốn một vòng đi-về, TLS 1.2 tốn hai, phiên được nối lại thì không tốn. Trên kết nối lạnh xuyên đại dương, riêng bước này đã hơn một trăm ms.",
   r:"The 'SSL' segment of a request timing in the browser. If it shows on every request rather than the first, connections are not being reused."},
 keepalive:{w:"Keep-alive (connection reuse)",
   p:"Using the same TCP and TLS connection for the next request instead of building a new one. The second request skips DNS, the TCP handshake and the TLS handshake — three round trips gone. It is the single cheapest latency fix that exists, and it is a configuration flag, not code.",
   v:"Dùng lại kết nối TCP và TLS cho request tiếp theo thay vì dựng mới. Request thứ hai bỏ qua DNS, bắt tay TCP và TLS — mất ba vòng đi-về là mất hết. Cách giảm độ trễ rẻ nhất, và chỉ là một cờ cấu hình.",
   r:"The connection pool in every HTTP client and every database driver. When it is missing, the waterfall shows a handshake on every single request."},
 nplusone:{w:"N+1 query",
   p:"One query to fetch a list, then one more query for each item in it. Forty rows becomes forty-one trips to the database, and each trip costs a round trip plus the query. The database is not slow; it is being asked forty-one times when once would do.",
   v:"Một truy vấn lấy danh sách, rồi thêm một truy vấn cho mỗi phần tử. Bốn mươi dòng thành bốn mươi mốt chuyến đi đến database. Database không chậm — nó bị hỏi bốn mươi mốt lần thay vì một.",
   r:"A list screen whose load time grows with the number of rows on it. The query log shows the same statement repeated with different ids."},
 tail:{w:"Tail latency (p99)",
   p:"The slow end of the distribution — the one request in a hundred, or a thousand, that takes many times longer than the typical one. Averages hide it completely. It comes from things that happen occasionally: a garbage collection pause, a lock, a cache miss, a retry.",
   v:"Đuôi chậm của phân bố — một trên trăm hay trên nghìn request chậm gấp nhiều lần bình thường. Trung bình che mất hoàn toàn. Nó đến từ những việc thỉnh thoảng xảy ra: dừng thu gom rác, khoá, cache miss, retry.",
   r:"The p99 line on the latency graph. A user who makes ten requests to load one screen meets the p99 about one time in ten."},
 loadbalancer:{w:"Load balancer",
   p:"The one address the outside world knows, which hands each request to one of several identical servers behind it. It also stops sending to a server that stops answering its health check. Inside the datacenter it costs a fraction of a millisecond.",
   v:"Địa chỉ duy nhất bên ngoài biết, chia mỗi request cho một trong nhiều server giống nhau phía sau, và ngừng gửi cho server không trả lời health check. Trong trung tâm dữ liệu nó tốn chưa đến một ms.",
   r:"The box with the public IP. Its request-per-second and error-rate graphs are the first two dashboards anyone opens in an incident."},
 dau:{w:"Daily active users (DAU)",
   p:"How many distinct people use the system on a typical day. It is the input every estimate starts from, because requests, writes and bytes are all 'per user per day' multiplied by it.",
   v:"Số người dùng khác nhau trong một ngày bình thường. Là đầu vào mọi ước lượng bắt đầu từ đó, vì request, ghi và byte đều là 'mỗi người mỗi ngày' nhân với nó.",
   r:"The analytics dashboard's headline number — and the one most often quoted as a hope rather than a measurement."},
 peak:{w:"Peak factor",
   p:"How much busier the busiest moment is than the daily average. Traffic is not spread evenly across 86,400 seconds; a rule of thumb is that peak is two to three times the average, and a launch, a sale or a news event can be ten. Design for the peak, pay for the average.",
   v:"Lúc đông nhất đông hơn trung bình ngày bao nhiêu lần. Lưu lượng không rải đều 86.400 giây; kinh nghiệm là đỉnh gấp hai đến ba lần trung bình, ra mắt hay khuyến mãi có thể gấp mười. Thiết kế cho đỉnh, trả tiền cho trung bình.",
   r:"The daily shape of the request graph. The gap between its top and its mean is the number your autoscaling rules are really about."},
 bandwidth:{w:"Bandwidth",
   p:"Bytes per second moving in or out, usually quoted in bits: a gigabit link carries about 125 megabytes a second. It is requests a second multiplied by the size of each response — which is how a modest request rate serving images becomes the most expensive line on the bill.",
   v:"Byte mỗi giây đi vào hoặc ra, thường tính bằng bit: đường 1 gigabit chở khoảng 125 megabyte một giây. Bằng số request mỗi giây nhân kích thước mỗi phản hồi — vì thế một lượng request khiêm tốn phục vụ ảnh lại thành dòng đắt nhất trên hoá đơn.",
   r:"The egress line on the cloud bill, and the reason a CDN exists."},
 iops:{w:"IOPS",
   p:"Input/output operations per second — how many separate reads or writes a disk can do. A spinning disk manages a few hundred; an SSD tens of thousands. Random access is what costs; sequential is nearly free by comparison.",
   v:"Số thao tác đọc/ghi riêng lẻ một đĩa làm được mỗi giây. Đĩa quay được vài trăm; SSD vài chục nghìn. Truy cập ngẫu nhiên mới tốn; tuần tự gần như miễn phí so với nó.",
   r:"The disk-queue graph on the database host. When it is flat at the ceiling, no amount of CPU will help."},
 payload:{w:"Payload",
   p:"The size of one thing being stored or sent — a row, a message, a photo. Multiplying it by a count is how a request rate becomes a storage figure or a bandwidth figure, and getting it wrong by a factor of ten is the most common way an estimate goes wrong.",
   v:"Kích thước một thứ được lưu hoặc gửi — một dòng, một tin nhắn, một tấm ảnh. Nhân với số lượng là cách biến tốc độ request thành con số lưu trữ hay băng thông; sai gấp mười ở đây là lỗi ước lượng phổ biến nhất.",
   r:"The average row size in the table statistics, or the average object size in the bucket. Look before you assume."},
 orderofmagnitude:{w:"Order of magnitude",
   p:"A power of ten. An estimate is right when it lands in the correct power of ten and wrong when it does not; the digits after that are noise. 'About a hundred a second' and 'about a thousand a second' are different designs; 116 and 140 are the same one.",
   v:"Một luỹ thừa của mười. Ước lượng đúng khi rơi vào đúng bậc mười, sai khi không; các chữ số sau đó chỉ là nhiễu. 'Khoảng một trăm mỗi giây' và 'khoảng một nghìn' là hai thiết kế khác nhau; 116 và 140 là một.",
   r:"The reason capacity numbers in a good design doc end in zeros."},
 hotset:{w:"Hot set (the 80/20 rule)",
   p:"The small share of items that get most of the traffic — roughly a fifth of the items take four fifths of the reads. It is the reason a cache far smaller than the data can still answer most requests, and the rule of thumb for how big that cache should be.",
   v:"Phần nhỏ dữ liệu nhận phần lớn lưu lượng — khoảng một phần năm số mục chiếm bốn phần năm lượt đọc. Vì thế cache nhỏ hơn dữ liệu nhiều vẫn trả lời được đa số request, và đó là quy tắc ước tính cache cần bao lớn.",
   r:"The cache hit rate. If a cache a tenth the size of the data hits nine times in ten, the rule held; if it hits half the time, the traffic is flatter than you assumed."},
 retention:{w:"Retention",
   p:"How long data is kept before it may be deleted. It is the multiplier that turns storage-a-year into the number on the disk, and it is a business decision — legal, product, cost — that the estimate has to ask about rather than assume.",
   v:"Dữ liệu được giữ bao lâu trước khi được phép xoá. Là hệ số biến lưu-trữ-mỗi-năm thành con số thật trên đĩa, và là quyết định nghiệp vụ — pháp lý, sản phẩm, chi phí — mà ước lượng phải hỏi chứ không được giả định.",
   r:"The lifecycle rule on the bucket, and the archive job nobody remembers writing."},
 stateless:{w:"Stateless server",
   p:"A server that keeps nothing between requests that the next request would need. Everything a request depends on — who the user is, what is in their cart, the file they just uploaded — lives somewhere every server can reach. The consequence is the whole point: any server can answer any request, so servers can be added, removed, restarted and replaced without a user noticing.",
   v:"Server không giữ gì giữa hai request mà request sau cần đến. Mọi thứ request phụ thuộc — người dùng là ai, giỏ hàng, file vừa tải — nằm ở chỗ mọi server đều với tới. Hệ quả là toàn bộ ý nghĩa: server nào cũng trả lời được request nào, nên thêm, bớt, khởi động lại, thay thế đều không ai nhận ra.",
   r:"A deploy that nobody notices, and an autoscaler that can add a server at 8pm and remove it at midnight."},
 session:{w:"Session",
   p:"What the server remembers about a user between requests: that they logged in, who they are, what they were doing. It has to live somewhere, and where it lives decides whether a second server is possible — in one server's memory it is stranded; in a shared store or a signed token it is reachable from anywhere.",
   v:"Những gì server nhớ về một người dùng giữa các request: đã đăng nhập, là ai, đang làm gì. Nó phải nằm ở đâu đó, và nằm ở đâu quyết định có thêm được server thứ hai hay không — trong bộ nhớ một server thì mắc kẹt; trong kho dùng chung hay token có chữ ký thì chỗ nào cũng với tới.",
   r:"The session cookie in the browser, and the row or key it points at — or, with a signed token, the cookie is the session."},
 sticky:{w:"Sticky sessions",
   p:"A load-balancer setting that sends every request from one user to the same server, so that a session kept in that server's memory keeps being found. It works, and it is a crutch: load drifts uneven, a server that dies takes its users with it, and a deploy still restarts the memory. Fine for a week; write down the date it comes off.",
   v:"Cài đặt của load balancer gửi mọi request của một người dùng về cùng một server, để session nằm trong bộ nhớ server đó vẫn được tìm thấy. Nó chạy được, và là cái nạng: tải lệch dần, server chết kéo theo người dùng của nó, deploy vẫn xoá bộ nhớ. Dùng một tuần thì được; ghi ngày bỏ nó.",
   r:"A cookie the load balancer sets naming the server, and one server in the pool that is always busier than the rest."},
 healthcheck:{w:"Health check",
   p:"A request the load balancer makes to each server every few seconds to decide whether to keep sending it traffic. A shallow check answers 200 as long as the process is up, even when it cannot reach its database; a deep check fails whenever a dependency blinks and can take every server out at once. The honest check tests what the server itself controls.",
   v:"Request load balancer gửi tới từng server vài giây một lần để quyết định có tiếp tục gửi traffic không. Check nông trả 200 miễn là process còn sống, kể cả khi không nối được database; check sâu thất bại mỗi khi một phụ thuộc chớp, và có thể hạ mọi server cùng lúc. Check trung thực kiểm tra thứ chính server kiểm soát.",
   r:"The /health endpoint, and the load balancer's target list showing which servers are in and out of rotation."},
 horizontal:{w:"Horizontal scaling",
   p:"Adding more servers, as opposed to a bigger one. It only works once servers are interchangeable — which is what stateless means — and it is the move that has no ceiling: a bigger machine eventually does not exist; a tenth machine always does.",
   v:"Thêm nhiều server thay vì một server to hơn. Chỉ làm được khi các server thay thế được cho nhau — chính là stateless — và là nước đi không có trần: máy to hơn nữa đến lúc không tồn tại; máy thứ mười thì luôn có.",
   r:"The instance count on the autoscaling group, and the moment it first goes from 1 to 2."},
 rollingdeploy:{w:"Rolling deploy",
   p:"Replacing servers one at a time with the new version while the others keep serving, so that the system never goes down for a release. Every process restarts once. Anything that lived only in a process is gone — which is how a deploy becomes the event that logs every user out.",
   v:"Thay từng server một sang phiên bản mới trong khi các server khác vẫn phục vụ, nên hệ thống không bao giờ dừng để phát hành. Mỗi process khởi động lại một lần. Thứ gì chỉ nằm trong process thì mất — đó là cách một lần deploy trở thành sự kiện đăng xuất toàn bộ người dùng.",
   r:"The deploy log showing servers leaving and rejoining the pool one by one — and the login graph spiking right after, if sessions were in memory."},
 stateless:{w:"Stateless server",
   p:"A server that keeps nothing between requests that the next request would need. Everything a request depends on — who the user is, what is in their cart, the file they just uploaded — lives somewhere every server can reach. The consequence is the whole point: any server can answer any request, so servers can be added, removed, restarted and replaced without a user noticing.",
   v:"Server không giữ gì giữa hai request mà request sau cần đến. Mọi thứ request phụ thuộc — người dùng là ai, giỏ hàng, file vừa tải — nằm ở chỗ mọi server đều với tới. Hệ quả là toàn bộ ý nghĩa: server nào cũng trả lời được request nào, nên thêm, bớt, khởi động lại, thay thế đều không ai nhận ra.",
   r:"A deploy that nobody notices, and an autoscaler that can add a server at 8pm and remove it at midnight."},
 session:{w:"Session",
   p:"What the server remembers about a user between requests: that they logged in, who they are, what they were doing. It has to live somewhere, and where it lives decides whether a second server is possible — in one server's memory it is stranded; in a shared store or a signed token it is reachable from anywhere.",
   v:"Những gì server nhớ về một người dùng giữa các request: đã đăng nhập, là ai, đang làm gì. Nó phải nằm ở đâu đó, và nằm ở đâu quyết định có thêm được server thứ hai hay không — trong bộ nhớ một server thì mắc kẹt; trong kho dùng chung hay token có chữ ký thì chỗ nào cũng với tới.",
   r:"The session cookie in the browser, and the row or key it points at — or, with a signed token, the cookie is the session."},
 sticky:{w:"Sticky sessions",
   p:"A load-balancer setting that sends every request from one user to the same server, so that a session kept in that server's memory keeps being found. It works, and it is a crutch: load drifts uneven, a server that dies takes its users with it, and a deploy still restarts the memory. Fine for a week; write down the date it comes off.",
   v:"Cài đặt của load balancer gửi mọi request của một người dùng về cùng một server, để session nằm trong bộ nhớ server đó vẫn được tìm thấy. Nó chạy được, và là cái nạng: tải lệch dần, server chết kéo theo người dùng của nó, deploy vẫn xoá bộ nhớ. Dùng một tuần thì được; ghi ngày bỏ nó.",
   r:"A cookie the load balancer sets naming the server, and one server in the pool that is always busier than the rest."},
 healthcheck:{w:"Health check",
   p:"A request the load balancer makes to each server every few seconds to decide whether to keep sending it traffic. A shallow check answers 200 as long as the process is up, even when it cannot reach its database; a deep check fails whenever a dependency blinks and can take every server out at once. The honest check tests what the server itself controls.",
   v:"Request load balancer gửi tới từng server vài giây một lần để quyết định có tiếp tục gửi traffic không. Check nông trả 200 miễn là process còn sống, kể cả khi không nối được database; check sâu thất bại mỗi khi một phụ thuộc chớp, và có thể hạ mọi server cùng lúc. Check trung thực kiểm tra thứ chính server kiểm soát.",
   r:"The /health endpoint, and the load balancer's target list showing which servers are in and out of rotation."},
 horizontal:{w:"Horizontal scaling",
   p:"Adding more servers, as opposed to a bigger one. It only works once servers are interchangeable — which is what stateless means — and it is the move that has no ceiling: a bigger machine eventually does not exist; a tenth machine always does.",
   v:"Thêm nhiều server thay vì một server to hơn. Chỉ làm được khi các server thay thế được cho nhau — chính là stateless — và là nước đi không có trần: máy to hơn nữa đến lúc không tồn tại; máy thứ mười thì luôn có.",
   r:"The instance count on the autoscaling group, and the moment it first goes from 1 to 2."},
 rollingdeploy:{w:"Rolling deploy",
   p:"Replacing servers one at a time with the new version while the others keep serving, so that the system never goes down for a release. Every process restarts once. Anything that lived only in a process is gone — which is how a deploy becomes the event that logs every user out.",
   v:"Thay từng server một sang phiên bản mới trong khi các server khác vẫn phục vụ, nên hệ thống không bao giờ dừng để phát hành. Mỗi process khởi động lại một lần. Thứ gì chỉ nằm trong process thì mất — đó là cách một lần deploy trở thành sự kiện đăng xuất toàn bộ người dùng.",
   r:"The deploy log showing servers leaving and rejoining the pool one by one — and the login graph spiking right after, if sessions were in memory."},
 sli:{w:"SLI — service level indicator",
   p:"A number that measures one aspect of how well the service is doing its job: the fraction of requests that succeed, or that return within 200 ms. It is the raw measurement, taken from real traffic, that everything else is built on.",
   v:"Chỉ số đo một khía cạnh chất lượng dịch vụ: tỷ lệ request thành công, hay tỷ lệ trả về dưới 200 ms. Là con số đo thô từ traffic thật, nền của mọi thứ phía trên.",
   r:"A specific line on a dashboard — success rate, p99 latency — computed from real requests, not from a synthetic ping."},
 slo:{w:"SLO — service level objective",
   p:"The target you set for an SLI: 99.9% of requests succeed over a rolling 30 days. It is an internal promise the team designs and operates against, and it is where the argument about how many nines is worth paying for actually happens.",
   v:"Mục tiêu đặt cho SLI: 99,9% request thành công trong 30 ngày gần nhất. Là lời hứa nội bộ đội ngũ thiết kế và vận hành theo, và là nơi tranh luận 'bao nhiêu số chín thì đáng trả tiền' thực sự diễn ra.",
   r:"The threshold an alert fires against, and the number a launch-readiness review is really asking about."},
 sla:{w:"SLA — service level agreement",
   p:"The SLO written into a contract, with money attached: if availability drops below the promised figure, the customer gets credits. An SLA is always a little looser than the internal SLO, so that missing the target is a warning to the team before it is a refund to the customer.",
   v:"SLO viết vào hợp đồng, kèm tiền: tụt dưới mức đã hứa thì khách được đền tín dụng. SLA luôn lỏng hơn SLO nội bộ một chút, để hụt mục tiêu là lời cảnh báo cho đội trước khi thành khoản hoàn tiền cho khách.",
   r:"The uptime clause in the customer contract, and the credit the finance team pays out when it is missed."},
 errorbudget:{w:"Error budget",
   p:"The downtime an SLO permits — the other side of the nines. A 99.9% target is a 0.1% budget, about 43 minutes a month, to spend on risky deploys, experiments and the occasional incident. Spend it and you slow down; save it and you can move faster. It turns reliability from a wish into an amount.",
   v:"Thời gian chết mà SLO cho phép — mặt kia của số chín. Mục tiêu 99,9% là ngân sách 0,1%, khoảng 43 phút mỗi tháng, để tiêu vào deploy mạo hiểm, thử nghiệm và sự cố. Tiêu hết thì chậm lại; để dành thì đi nhanh hơn.",
   r:"The gap between the SLO and 100%, tracked as a balance that deploys and incidents draw down."},
 cap:{w:"CAP theorem",
   p:"When the network between two copies of your data splits — a partition — you can keep the copies consistent or keep the system available, but not both until the split heals. Consistency and availability are only in tension during a partition; the rest of the time you can have both. The theorem is not a menu of three; it is a forced choice of one, made only when the network fails.",
   v:"Khi mạng giữa hai bản sao dữ liệu đứt — một phân mảnh — bạn giữ được nhất quán hoặc giữ được sẵn sàng, không cả hai cho tới khi mạng lành. Hai thứ chỉ mâu thuẫn lúc phân mảnh; lúc khác có cả hai. Không phải thực đơn ba món, mà là chọn ép một, chỉ khi mạng hỏng.",
   r:"The reason a database's docs have a page on 'behaviour during a network partition', and the sentence in a design doc that says which side of it you chose."},
 partitionnet:{w:"Network partition",
   p:"A break in the network that leaves two parts of the system unable to reach each other, while each may still be reachable by clients. It is not a machine failing — both sides are alive — it is the wire between them failing. Rare, brief, and the exact moment CAP forces its choice.",
   v:"Đứt mạng khiến hai phần hệ thống không với được nhau, dù mỗi phần vẫn có thể được client truy cập. Không phải máy chết — cả hai bên còn sống — mà là sợi dây giữa chúng chết. Hiếm, ngắn, và đúng lúc CAP ép phải chọn.",
   r:"A spike in cross-region timeouts with both regions reporting healthy — the signature of a split rather than an outage."},
 cp:{w:"CP — consistency during a partition",
   p:"The choice to refuse any write that cannot be confirmed across the split, so that every copy stays in agreement. Users on the cut-off side get errors on writes for the length of the partition; nobody ever reads a wrong value. The right default for money, inventory and bookings, where two truths is worse than a pause.",
   v:"Chọn từ chối mọi write không xác nhận được qua chỗ đứt, để mọi bản sao luôn nhất trí. Người dùng ở phía bị cắt bị lỗi khi ghi suốt thời gian phân mảnh; không ai đọc trúng giá trị sai. Mặc định đúng cho tiền, tồn kho, đặt chỗ — nơi hai sự thật tệ hơn một lần tạm dừng.",
   r:"A database configured to require a quorum for writes, returning errors rather than diverging when it cannot reach one."},
 ap:{w:"AP — availability during a partition",
   p:"The choice to accept writes on whichever copy a client can reach, so the system never returns an error — at the price that the copies disagree until the split heals and must then be reconciled. The right default for likes, feeds, status pages and carts, where a brief disagreement is cheaper than an outage.",
   v:"Chọn nhận write ở bất kỳ bản sao nào client với tới, để hệ thống không bao giờ báo lỗi — đổi lại các bản sao lệch nhau đến khi mạng lành rồi phải hoà giải. Mặc định đúng cho like, feed, trang trạng thái, giỏ hàng — nơi lệch nhau một lúc rẻ hơn một lần sập.",
   r:"A store that takes writes on any node and resolves conflicts afterward with last-write-wins or a merge rule."},
 eventual:{w:"Eventual consistency",
   p:"The promise that if writes stop, all copies will agree — eventually, usually within seconds. It does not say when, only that they converge. It is what AP systems offer, and it is fine for a great many things and quietly wrong for a few, so the question is always which thing this is.",
   v:"Lời hứa rằng nếu ngừng ghi, mọi bản sao sẽ nhất trí — dần dần, thường trong vài giây. Không nói khi nào, chỉ nói chúng hội tụ. Đó là thứ hệ AP cung cấp, đúng cho rất nhiều việc và lặng lẽ sai cho vài việc — nên câu hỏi luôn là: đây là việc nào.",
   r:"The replication-lag graph settling back to zero after a write, and the rare read served before it did."}
};
